### ISSUE TITLE
Dataset upload

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#10]
After uploading the dataset, Lemonade should go back to the 'Data Sources' page, showing a message of success such as "Your dataset was successfully uploaded."

Depending on the person who is using the system, receiving a message and  going back to the 'Data Sources' page may be more intuitive.

**Comment by waltersf** [comment]
Done. Also adapted the upload to automatically call the infer schema. In case of error in the infer step, the upload may succeed even with the error.

**Comment by alexgcsa** [comment]
Hi Walter,

Tested. It works fine.

Alex
