### ISSUE TITLE
Translate the result of generalized linear regression to Portuguese (PT-BR)

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#104]
Currently, everything is in English (subtitles, tables, etc):

![image](https://user-images.githubusercontent.com/24958541/54640995-d52f8f80-4a6f-11e9-946c-d706b6ce304d.png)

**Comment by waltersf** [comment]
@alexgcsa Could you please provide the correct Portuguese names for these fields?

**Comment by alexgcsa** [comment]
Sure.

Replace "Prediction" by "Predição".
Replace "Residual" by "Residuos".
Replace "Summary" by "Resultado da Avaliação", like it happens in the classification framework.

I would change all names in the table to Portuguese (pt-br):


Replace "coefficientStandardErrors" by 
Replace "degreesOfFreedom" by "Graus de Liberdade"
Replace "devianceResiduals" by "Desvio dos Residuos"
Replace "explainedVariance" by "Variância Explicada"
Replace "featuresCol" by "Coluna(s) de atributos"
Replace "labelCol" by "Coluna do rótulo"
Replace "meanAbsoluteError" by "Erro Absoluto Médio"
Replace "meanSquaredError" by "Erro Quadrático Médio" 
Repalce "numInstances" by "Número de Instâncias"
Replace "objectiveHistory" by "Histórico do Objetivo" ?
Replace "pValues" by "Valores de p (p-values)"
Replace "predictionCol" by "Coluna de Predição"
Replace "predictions" by "Predições"
Replace "r2" by "Coeficiente de determinação (R²)"
Replace "r2adj" by "Coeficiente de Determinação Ajustado" (Adjusted R²)" 
Replace "residuals" by "Residuos"
Replace "rootMeanSquaredError" by "Raiz do Erro Quadrático Médio"
Replace "tValues" by "Estatística-t (t-value)"
Replace "totalIterations" by "Total de Iterações"

**Comment by waltersf** [comment]
Fixed. Please, review it.
