### ISSUE TITLE
Linear regression: duplicated hyper-parameter?

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#106]
Not sure if it is the same hyper-parameter, but we have in linear regression a hyper-parameter called "regularização" and another called "parâmetro de regularização".

Are they representing the same thing?

![image](https://user-images.githubusercontent.com/24958541/54696649-f72a2000-4b0a-11e9-96e1-13a04d85f879.png)

**Comment by waltersf** [comment]
Fixed. Both, regularization and iterations (max) are not duplicated anymore.
