### ISSUE TITLE
Change the name of a (general) hyper-parameter - k-fold cross-validation

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#108]
Hello,

We can discuss this latter, but I believe the name of a hyper-parameter that refers to the number of folds is a bit misleading:

![image](https://user-images.githubusercontent.com/24958541/54829820-02f61d80-4c96-11e9-9d57-abe3dd46dcf1.png)

I would replace "Atributo com o número da partição (fold)" by "Número de partições (folds) na validação cruzada".

**Comment by waltersf** [comment]
No, it is not the number, but the attribute with the fold information. Remember, Gustavo implemented an operation that splits data in folds and the fold number is in this column. The split is not performed by other operations.

**Comment by alexgcsa** [comment]
I forgot to close this issue. I understood better when I tried to use again.
