### ISSUE TITLE
Autosaving

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#11]
As a suggestion, I recommend to automatically save the workflow for the user (e.g., every five minutes the system automatically saves the workflow).

Or even a message warning possible data lost if the user decides to change from the current environment to another: 
"Do you want save the workflow before leaving? [Yes/No]"

**Comment by waltersf** [comment]
Second suggestion implies this issue is duplicate of #76

**Comment by waltersf** [comment]
Duplicate of #76

**Comment by alexgcsa** [comment]
Alright.

Thanks,

Alex
