### ISSUE TITLE
Problema coma operação Agrupar Linhas por Função

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#111]
Fluxo ID 122 

Eu especifiquei a utilização do atributo Pclass para fazer o agrupamento, porém o resultado utiliza outro atributo para executar a operação (atributo Name).

O objetivo era reproduzir o fluxo do documento Basic Usage (https://docs.google.com/document/d/1DXOjC-xTOWQKzbldizByfDOPzYaOaHmkTo5SdZVztrw/edit?usp=sharing), página 42,  conforme solicitado pela Gisele.

**Comment by waltersf** [comment]
@matheusrleal O problema é com a base de entrada. Ela está com quebras de linhas e vários outros problemas. Tentei abri-la no LibreOffice e não está bem formatada. Tente usar outra base e por favor, desabilite esta.
