### ISSUE TITLE
What is the reason of "Tags" in a dataset?

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#113]
Are these tags important?

![image](https://user-images.githubusercontent.com/24958541/55290166-011f0f00-53a6-11e9-97f0-f0ea29134533.png)

**Comment by alexgcsa** [comment]
Besides, the description should be translated.

**Comment by waltersf** [comment]
> Are these tags important?
> 
> ![image](https://user-images.githubusercontent.com/24958541/55290166-011f0f00-53a6-11e9-97f0-f0ea29134533.png)

You can group data sources by using tags or use them to describe the purpose of the data set. For instance, you could use tags "beginner", "advanced" or "classification", "clustering".

**Comment by alexgcsa** [comment]
Understood.

**Comment by waltersf** [comment]
Not a problem
