### ISSUE TITLE
Problema com a operação Filtrar por função

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#116]
Fluxo ID 122

Após executar um fluxo bem sucedido com a operação Filtrar por função ela exibe um erro ao retornar para a tela do fluxo. 
Ao abrir a janela da função e apertar Ok sem fazer nenhuma alteração o erro some, porém o fluxo não pode ser executado se isso não for feito.

**Comment by waltersf** [comment]
Fixed
