### ISSUE TITLE
Problema com a opção Salvar como uma imagem

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#117]
Fluxo ID 185

Quando o fluxo é muito grande e ultrapassa as bordas de uma página, a imagem resultante da opção Salvar como uma imagem fica incompleta, mesmo diminuindo o Zoom na janela do fluxo.

![workflow_185](https://user-images.githubusercontent.com/14841688/55433100-05e0f000-556b-11e9-9899-00c53617d07c.png)

**Comment by alexgcsa** [comment]
@matheusrleal , poderia retestar?

Aqui funcionou. mas não sei se ocorreu alguma mudança.

**Comment by waltersf** [comment]
Não, este problema é dependente do navegador, da versão e até da resolução.

**Comment by alexgcsa** [comment]
Oi Walter,

Ok. Vou fechar a issue então.

Quanto a mudança, estava me referindo ao do fluxo. Na imagem pareceu um pouco diferente.

Obrigado.

Alex
