### ISSUE TITLE
Default values of hyper-parameters are not appearing anymore

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#124]
The default values of hyper-parameters are not appearing anymore. I don't know why this is happening.

The problem is that several documentations I assumed that these default values were available.

**Comment by waltersf** [comment]
Please, provide the name of the operation and the workflow id.

**Comment by alexgcsa** [comment]
I will double check.
The issue is not on a specific workflow, but when you use an operation (e.g., classification or regression) from scratch.

**Comment by waltersf** [comment]
Not all operations are defined with default parameters. Which parameter and operation specifically?

**Comment by alexgcsa** [comment]
I am going to close this issue for now and change the documentation.

Thanks,

Alex
