### ISSUE TITLE
Annoying search filter

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#125]
It is really annoying when you try to search for a workflow/dataset, you are typing what you want to search, and it keeps updating and removing the letters/words you have just typed. I was wondering if there is anything to correct this?

It seems that Lemonade keeps updating everything on the search before the user finishes (pressing enter perhaps)

![image](https://user-images.githubusercontent.com/24958541/56871943-c981a200-69f9-11e9-8a8b-b5306867b191.png)

**Comment by waltersf** [comment]
It is a bug in the component that we use and it is not fixed.
I increased the debound timeout (time to wait before submitting the query).

**Comment by alexgcsa** [comment]
I think it is ok now. 

Sometimes it is still cutting some words. But it is much better now.

Thanks,

Alex
