### ISSUE TITLE
PCA issues

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#126]
Hi there, I will make a thread regarding PCA issues. I am using as reference the workflow 90.

1) Replace "Atributo para saída do ACP" by "Atributo para saída do PCA" or "Atributo de saída do PCA" or  simply "Atributo de saída".

2) I think "Atributo(s) de entrada" sounds better than "Atributo(s) previsor(es)".

![image](https://user-images.githubusercontent.com/24958541/56874782-9e577c80-6a12-11e9-826b-adc583052012.png)

**Comment by alexgcsa** [comment]
3) Besides, the output is very repetitive:

![image](https://user-images.githubusercontent.com/24958541/56874911-93e9b280-6a13-11e9-8f78-2ee48509c579.png)

**Comment by waltersf** [comment]
@alexgcsa Regarding the name of the input attributes, it is used in many operations. I think if we change this now, it'd be necessary to change the documentation.

**Comment by waltersf** [comment]
Problem with duplication fixed. Please, if it is OK, close this issue.

**Comment by alexgcsa** [comment]
Thanks, it is working fine now. 

The only issue is that it continues keeping attributes from the dataset that were not selected.

In the workflow 90 I didn't select the attribute "class" and this attribute appears in the result:

![image](https://user-images.githubusercontent.com/24958541/56901199-fc657d80-6a6d-11e9-8610-fea5d36f1ca1.png)

**Comment by waltersf** [comment]
@alexgcsa It is the expected behavior. PCA just add a new column to the input data frame.
