### ISSUE TITLE
LSH issues

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#127]
Similar to #126. 

I will describe in the following items (using the workflow 92 as reference):

0. In the description, replace "Locality-sensitive hashing (LSH)" by "Hashing sensível a contexto (Locality-sensitive hashing ou LSH)". And "itess" by "itens".

![image](https://user-images.githubusercontent.com/24958541/56904078-f4a8d780-6a73-11e9-9a5b-4563efcea371.png)

1. Replace "Atributo para saída" by  "Atributo de saída".

2. Replace "Tamanho do bucket (apenas para **Bucketd** Random Projection LSH)" by "Tamanho do bucket (apenas para 'Projeção aleatória em buckets para distância euclidiana')".

4. Into "Tipo do LSH", replace "Min Hash LSH  para distância de **Jackard**" by "Min Hash LSH  para distância de **Jaccard**";

![image](https://user-images.githubusercontent.com/24958541/56903889-8e23b980-6a73-11e9-80a4-8344f214e209.png)

5. Besides, the output is also very repetitive and including attributes not selected by the user (in this case, the attribute "class"):

![image](https://user-images.githubusercontent.com/24958541/56903855-7ea47080-6a73-11e9-8944-33a320c81927.png)

**Comment by waltersf** [comment]
@alexgcsa The translation of "Locality" as "Context" is not good. There is no result in Google, for example. Maybe in this case, it is better to keep the English term.

**Comment by alexgcsa** [comment]
@waltersf , I'm going to talk to Gisele tomorrow. Perhaps the operation name is misleading.

I've found the name "Hash sensível a localidade" here.

**Comment by alexgcsa** [comment]
I'm going just check the name of the operation with Gisele today just before closing this issue.

**Comment by alexgcsa** [comment]
@zilton / @waltersf , could you change the name of the operation, but maintaining the acronym in English:

Replace "Hashing sensível a contexto" by "Hash sensível à localidade (LSH)"

?


In its description, I would change "Locality-sensitive hashing (LSH)" by "Hash sensível à localidade (_Locality-sensitive hashing_ ou LSH) reduz a quantidade de...".

**Comment by alexgcsa** [comment]
Tested. It is fine.

Thanks,

Alex
