### ISSUE TITLE
Validação na Operação desabilitada

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#13]
Fluxo 31

Operação está desabilitada e ao executar o fluxo da erro nas operações que estão desabilitadas.
![image](https://user-images.githubusercontent.com/13971769/52119425-30144100-2600-11e9-9ac0-e1138ad50ceb.png)

Erros:

![image](https://user-images.githubusercontent.com/13971769/52119457-44f0d480-2600-11e9-98b3-048e3f25e981.png)

**Comment by waltersf** [comment]
Corrigido. Em qualquer caso, se um bug persistir, pode reabrir a issue.
