### ISSUE TITLE
Problema com a opção exibir amostra de resultados

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#139]
Como mencionado anteriormente, esse foi um problema identificado por um aluno em sala de aula, portanto não tenho um fluxo de referência para indicar.

Na situação apresentada pelo aluno o fluxo estava todo correto e funcionando, porém ao habilitar a opção de Exibir Amostra de Resultados em algumas operações no meio do fluxo, um erro era apresentado e o fluxo não era executado.

**Comment by waltersf** [comment]
@matheusrleal Sabe ao menos o nome do usuário?

**Comment by alexgcsa** [comment]
@matheusrleal , você poderia testar essa issue?

**Comment by matheusrleal** [comment]
Vou precisar verificar com os alunos em sala de aula. Ainda não me deparei com o problema novamente.

**Comment by alexgcsa** [comment]
@matheusrleal , 

quando você se deparar com o problema novamente, você anota o usuário e id do fluxo. Em seguida, comente nessa issue e em todo caso o Walter ou eu reabrimos.

Att.,

Alex
