### ISSUE TITLE
Problema com o Box plot

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#140]
Fluxo ID 386

Nesse caso ocorreu um problema na identificação de mínimo, máximo e outliers na base de dados.

![image](https://user-images.githubusercontent.com/14841688/57791069-63dc2800-7712-11e9-9e1e-db2f3d2b03c9.png)

**Comment by zilton** [comment]
Matheus,

subimos uma versão do box-plot.

Façam testes e verifiquem se está tudo funcionando corretamente, por favor.

Em caso de problemas, basta reportar por aqui.

Se estiver tudo correto, por favor, fechem a thread.

Obrigado.
