### ISSUE TITLE
Sugestão para o Inferir Esquema

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#141]
Atualmente, para que a maioria das operações funcione corretamente, é necessário que a base de dados tenha passado pelo processo de Inferir Esquema durante a etapa de importação. Quando esse processo não é realizado, nenhum erro ou aviso é apresentado e o usuário só se depara com uma mensagem de erro durante a execução de um fluxo, que também não indica que o problema está relacionado a isso. Portanto a sugestão é que a operação de Inferir Esquema seja executada por padrão quando o usuário clica em Salvar durante a importação da base de dados.

**Comment by alexgcsa** [comment]
@matheusrleal , você poderia testar?

**Comment by matheusrleal** [comment]
Funcionando.

**Comment by waltersf** [comment]
Segundo o @matheusrleal, está funcionando

**Comment by alexgcsa** [comment]
Issue aberta novamente a pedido do @matheusrleal .

**Comment by matheusrleal** [comment]
Depois da alteração, ao subir uma base de dados, o "inferir esquema" parece executar automaticamente, o que já possibilita utilizar a base nos fluxos de trabalho. No entanto, algumas bases de dados, como  a BreadBasket_DMS.csv (ID 989), apresentaram problemas, assim como algumas outras bases que os alunos escolheram. Acredito que tenha sido pela seleção automática do separador de dados, pois ao selecionar outro separador na tela de edição da base e executar o "inferir esquema" novamente, o problema é resolvido.
A sugestão de executar o "inferir esquema" junto com o botão salvar (ao invés de automaticamente) é mesmo inviável ?

**Comment by waltersf** [comment]
Matheus, 
Não entendi. "Inferir esquema" junto com o botão salvar é o que ocorre no upload. Dá no mesmo, a pessoa vai escolher qualquer separador e clicar o botão. 
Neste caso, a solução é orientar o usuário.
