### ISSUE TITLE
Erro de execução contínuo

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#143]
Problema identificado por alunos de ICD em sala de aula.

Ao adicionar todas as operações a um fluxo e preencher alguma delas de forma incorreta, o fluxo apresenta um erro e para de funcionar. Por mais que a operação incorreta seja corrigida, o erro de execução permanece, mesmo excluindo todas as operações e adicionando novamente.
A única forma de solucionar o problema é criar um fluxo novo e começar o processo novamente.

**Comment by waltersf** [comment]
@matheusrleal Não há como resolvermos sem um fluxo. Sabe ao menos o nome do usuário?

**Comment by matheusrleal** [comment]
Vou procurar na próxima aula prática e tentar registrar quando acontecer futuramente.

**Comment by alexgcsa** [comment]
Oi pessoal,

Isso aconteceu no fluxo 849 a pouco tempo (ambiente de testes).

Att.,

Alex

**Comment by matheusrleal** [comment]
Exemplos de usuários que encontraram esse problema:
- josianefx@gmail.com -> Fluxo ID 853
- marcinhalisboa@yahoo.com.br -> Fluxo ID 850
- thaissalages@ufmg.br -> Fluxo ID 857
- wfabian52@eci.ufmg.br -> Fluxo ID878

O problema ocorre sempre após o usuário executar o fluxo com algum tipo de problema (operações não preenchidas ou preenchidas incorretamente). A partir disso, o fluxo inteiro trava e não executa mais nada (inclusive o ícone de pause aparece embaixo de todas as operações).

O que eu já tentei fazer para solucionar o problema foi:
- Apagar a operação que gerou o problema e criar novamente.
- Apagar todas as operações do fluxo e começar novamente.
- Restaurar o fluxo para uma versão mais antiga no histórico.
- Excluir todas as execuções relacionadas ao fluxo e tentar novamente.
- Atualizar a página limpando o cache.

Porém nenhuma dessas alternativas solucionou o problema. A única forma que encontrei de continuar realizando a atividade foi criar um novo fluxo (novo ID) e começar tudo novamente.
A professora Ana Paula comentou que isso parece um problema de sobrecarga, devido ao fato de ter vários usuários ao mesmo tempo.

**Comment by waltersf** [comment]
Está reportando um erro:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 21: ordinal not in range(128).
É o "English dash"
https://www.fileformat.info/info/unicode/char/2013/index.htm.

O nome do fluxo está com esse caractere. Por exemplo: "Itemsets frequentes – THAISSA". 
Não sei como conseguiram gerar este caractere no teclado.

**Comment by alexgcsa** [comment]
@waltersf , sobre o fluxo 849 você teria alguma ideia sobre o que está  ocorrendo?

Eu descrevi um pouco mais na issue #131 : 
 
"Just to detail more about it...I set the wrong attributes for random forest and, when I run it, it output an error. After that, I corrected the wrong attributes (they were categorical), but the error persisted.

However, when I copied and created the workflow 1036...And it worked."


Eu fiz uma nova cópia e funciona (1091)

Obrigado.

Alex

**Comment by matheusrleal** [comment]
Se for possível adicionar um botão "RESET" para resetar todas as operações realizadas no fluxo, incluindo parâmetros e conexões, mas sem deletar todo o fluxo, isso poderia ser uma alternativa.

**Comment by waltersf** [comment]
Eu fiz uma correção emergencial por conta do caractere maluco que estão usando e reiniciei todos as execuções. Parece estar ok agora. Esse povo tem entrega de trabalho? Tem muita gente rodando agora.

**Comment by matheusrleal** [comment]
Estava em horário de aula
