### ISSUE TITLE
Problema com a operação Junção

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#144]
Ao utilizar a operação Junção e deixar DESMARCADA a opção "Manter chaves da segunda fonte de dados", os atributos da segunda base de dados utilizados para fazer a junção são excluídos da tabela. No entanto, ao utilizar o resultado da Junção como entrada para qualquer outra operação, os atributos excluídos continuam aparecendo na lista de atributos. Ao selecionar qualquer um deles  na operação, o resultado é um erro de execução.

**Comment by waltersf** [comment]
Cancelada
