### ISSUE TITLE
Problema com a nova seleção de atributos

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#145]
Fluxo ID 822

O novo componente de seleção de atributos não está apresentando o comportamento esperado.

- Ao abri-lo pela primeira vez, não é possível selecionar somente um atributo, é preciso adicionar todos e depois remover os que não serão utilizados. 
- O campo de busca embaixo da janela permite inserir atributos que não existem na base de dados.
- Algumas operações não estão mais funcionando após a alteração (Ex.: Gráfico de barras do fluxo indicado)

Obs.: Ao sugerir uma alteração na forma de selecionar os atributos, a ideia adicionar somente um botão ou checkbox que permitisse selecionar todos de uma vez. Acredito que esse novo componente não seja ideal, pois adiciona uma série de novos cliques para realizar a mesma tarefa, além de parecer mais complexo para usuários leigos.

**Comment by waltersf** [comment]
> Fluxo ID 822
> 
> O novo componente de seleção de atributos não está apresentando o comportamento esperado.
> 
> * Ao abri-lo pela primeira vez, não é possível selecionar somente um atributo, é preciso adicionar todos e depois remover os que não serão utilizados.

A versão que subi agora deve ter corrigido isto.


> * O campo de busca embaixo da janela permite inserir atributos que não existem na base de dados.
Este não é um campo de busca, é um campo justamente para adicionar campos que não foram inferidos. Há casos onde não é possível inferir a base de dados ou o usuário simplesmente não quer. Daí ele tem que saber os nomes das colunas. 

> * Algumas operações não estão mais funcionando após a alteração (Ex.: Gráfico de barras do fluxo indicado)
A versão que subi agora deve ter corrigido isto.

> Obs.: Ao sugerir uma alteração na forma de selecionar os atributos, a ideia adicionar somente um botão ou checkbox que permitisse selecionar todos de uma vez. Acredito que esse novo componente não seja ideal, pois adiciona uma série de novos cliques para realizar a mesma tarefa, além de parecer mais complexo para usuários leigos.

Matheus, a quantidade de cliques é a mesma, exceto que uma janela é aberta. Mesmo com checkboxes, a janela teria de ser aberta porque poderia haver tantos campos que a tela de propriedades iria ficar bem ruim. Sobre ser mais complexo, seria necessário testar com eles. A caixa é bem similar às encontradas no Knime (http://marcoghislanzoni.com/blog/wp-content/uploads/2016/05/c6324675ff3a6ec5bb4be96a6edca9fb.png) e no Azure ML Studio (https://docs.microsoft.com/en-us/azure/machine-learning/studio/media/tutorial-part1-credit-risk/select-columns.png)

**Comment by alexgcsa** [comment]
@matheusrleal , você poderia testar?

**Comment by matheusrleal** [comment]
Está funcionando corretamente agora, porém esse problema ainda permanece:

- O campo de busca embaixo da janela permite inserir atributos que não existem na base de dados.

**Comment by waltersf** [comment]
"O campo de busca embaixo da janela permite inserir atributos que não existem na base de dados."
@matheusrleal este campo não é para busca, é para adicionar um campo que não foi possível inferir no pipeline. Isto pode acontecer porque a pessoa está usando uma base de dados onde ela está controlando os atributos ou por alguma causa onde o Lemonade não consegue a informação. Por exemplo, tem como fazer uma operação "Pivot Table" onde as linhas viram coluna. Não tem como saber isto sem processar e mesmo após processar, não dá para atualizar a interface. Estes casos requerem que seja permitido inserir o nome no atributo.

**Comment by alexgcsa** [comment]
@waltersf , talvez a gente tenha uma questão...

Essa parte de seleção de atributos já está no ambiente ICD.

Tem hora que coloco uma operação nova, eu clico no atributo, mas ele não é selecionado. Parece que trava a seleção.

Contudo, na hora que eu abro novamente a tela, parece que aquele atributo foi selecionado N vezes:


![image](https://user-images.githubusercontent.com/24958541/58330552-7c80c800-7e0d-11e9-9032-9e8d505a201d.png)


*Fluxo 9 no ambiente ICD*:
https://icd.ctweb.inweb.org.br/#/workflows/1/9

**Comment by alexgcsa** [comment]
Não é um problema já deixarmos essa versão da seleção de atributos no ambiente ICD?

**Comment by waltersf** [comment]
Considerando que os alunos estão usando a versão de teste, não é um problema.

**Comment by alexgcsa** [comment]
@waltersf , 

notei um erro na nova interface de seleção de atributos no último fim de semana enquanto estava ajudando os alunos do colégio militar.

Isso acontece na primeira abertura da interface, logo após criar um fluxo.

Por exemplo, se eu crio um fluxo e tento selecionar todos os atributos de uma vez, a interface não deixa. Eu tenho que pelo menos selecionar um primeiro e, em seguida, todos. Ou fechar a interface e tentar novamente.

Além disso, parece que a opção de "OK" não funciona.

Obrigado.

Alex

**Comment by waltersf** [comment]
Erro no console JS:
"Invalid attempt to spread non-iterable instance."

**Comment by waltersf** [comment]
Corrigido
