### ISSUE TITLE
Operação Filtrar não funciona

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#15]
Fluxo 31
1) Carreguei a base GlobalLandTemperaturesByCountry.csv
2) Inseri a operação Filtrar por função 1 e selecionei para filtrar **Country="Brazil"**
3) Verifiquei que o filtro funciona, em outra ferramenta, como pode ser visto na figura abaixo:
![image](https://user-images.githubusercontent.com/13971769/52120109-74084580-2602-11e9-9b36-413baa1ef452.png)
4) Mas o lemonade não retornou nada.
![image](https://user-images.githubusercontent.com/13971769/52120151-900be700-2602-11e9-8953-7f87cf78355e.png)

**Comment by waltersf** [comment]
A base de dados está no formato Windows, portanto, as quebras de linha são \r\n. O Spark usa como delimitador o que está configurado no sistema operacional, no caso, Linux. E o Spark não deixa mudar isto. Como solução paliativa, há como usar uma opção para remover espaços em excesso no final da coluna, ignoreTrailingWhiteSpace. No caso, Brazil estava sendo representado como "Brazil\r". 

Por favor, teste e feche a issue se ok.
