### ISSUE TITLE
Environment changing to English automatically

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#150]
Hi,

I noticed this when I was using the ICD/test environment...Sometimes the environment is changing the language (usually to English)  without being set to.

Could you check?

The problem is that I do not have a strict description for this.

Thanks,

Alex

**Comment by alexgcsa** [comment]
This usually happens when we run a workflow and come back to workflow environment.

**Comment by mgonc** [comment]
Can't reproduce this error, can you test again and informe us if still happening

**Comment by alexgcsa** [comment]
I am going to close it. If I detect again, I reopen this issue again.
