### ISSUE TITLE
Not possible to delete a comment box

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#153]
Hi @waltersf  / @zilton ,

Currently, it is impossible to delete a comment box. We should have a way to do it.

![image](https://user-images.githubusercontent.com/24958541/58659552-a2203c80-82f9-11e9-9184-f56032620eb3.png)

Could you check it?

The workflow id is 1032.

Cheers,

Alex

**Comment by waltersf** [comment]
Done. Please, test in ICD environment.

**Comment by alexgcsa** [comment]
Tested. It is working.

Thanks,

Alex
