### ISSUE TITLE
Gráficos não estão aparecendo

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#16]
Fluxo 32

O Fluxo executou sem erros, mas não exibiu o gráfico em resultados.
![image](https://user-images.githubusercontent.com/13971769/52120444-7b7c1e80-2603-11e9-975c-8c3b4e3235e5.png)
![image](https://user-images.githubusercontent.com/13971769/52120469-8e8eee80-2603-11e9-9873-a756c3601591.png)

**Comment by barbarasilveiraf** [comment]
Aconteceu isso com o fluxo 40 também. Gráfico de rosca

**Comment by barbarasilveiraf** [comment]
Aconteceu isso com o fluxo 44  também. Gráfico de pizza

**Comment by barbarasilveiraf** [comment]
Aconteceu isso com o fluxo 47 também. Tabela

**Comment by waltersf** [comment]
É relacionado à sincronização com a execução. Se pressionar F5, deve exibi-las. De qualquer forma, é um bug.

**Comment by barbarasilveiraf** [comment]
Testei com o gráfico de área, fluxo 31.
Apareceu a aba visualizações, mas não mostrou nenhum gráfico.

![image](https://user-images.githubusercontent.com/13971769/52176432-e2cbd700-2799-11e9-8a56-078fbcbb8b1a.png)

**Comment by sauloantuness** [comment]
No **fluxo 31**, o eixo x é uma variável do tipo _time_. As visualizações não suportam este tipo de dado.
Vou implementar o suporte a este tipo de variável.
