### ISSUE TITLE
Erro de digitação no campo "Filtrar por função"

### ISSUE THREAD

**Issue by lauranandrade** [eubr-bigsea/citrus#167]
O Filtrar por função, no campo "Expressão para filtro(avançado)", ao clicar em "Editar valor", o texto que aparece está com um erro de portugês, está escrito "Examplo" ao invés de "Exemplo".

**Comment by Rodrigovargasv** [comment]
Em Type Switch.
switch v := i.(type) {
Switch v := i.(type) {
case T:
    // aqui v tem o tipo T
case S:
    // aqui v tem o tipo S
default:
    // sem correspondênte; aqui V tem o mesmo tipo I
    // sem correspondente; aqui V tem o menos tipo I
}

**Comment by Rodrigovargasv** [comment]
Type Switch
switch v := i.(type) {
case T:
    // aqui v tem o tipo T
case S:
    // aqui v tem o tipo S
default:
    // sem correspondênte; aqui V tem o mesmo tipo I
}  // sem correspondente; aqui V tem o mesmo tipo I

**Comment by Rodrigovargasv** [comment]
Em Tipo Switch. 
switch v: = i. (tipo) { 
Alternar v: = i. (tipo) { 
caso T: 
// aqui v tem o tipo T 
caso S: 
// aqui v tem o tipo S 
padrão: 
// sem correspondênte; aqui V tem o mesmo tipo I 
// sem correspondente; aqui V tem o menos tipo I 
}
