### ISSUE TITLE
Mapas no Lemonade

### ISSUE THREAD

**Issue by zilton** [eubr-bigsea/citrus#176]
E-mail da Gisele: 
"""
Para o contexto da dengue, seria essencial utilizar uma visualização
em mapa para o Lemonade. Estou tentando fazer um mapa lá seguindo a
documentação sem sucesso, mas acho que encontrei a razão.

Diz na documentação que: "Atualmente o Lemonade suporta apenas um Mapa
Mundi e um mapa dos Estados Brasileiros."
Eu precisaria dos limites dos municípios, e isso tem disponível em geoJSON aqui:
https://github.com/tbrugz/geodata-br
"""

**Comment by waltersf** [comment]
Um problema com os limites dos municípios é que o geoJSON tem 30 MB.

**Comment by waltersf** [comment]
Teoricamente, esse problema foi resolvido. O mapa por Estado está ok.
