### ISSUE TITLE
Erro na operação Mapa

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#18]
Fluxo 42, ocorreu erro ao executar o fluxo.

![image](https://user-images.githubusercontent.com/13971769/52121953-838a8d00-2608-11e9-90b7-d999bc6be8c8.png)

**Comment by waltersf** [comment]
Bug aberto no Caipirinha

**Comment by barbarasilveiraf** [comment]
Na visualização de mapa do tipo pontos está funcionado agora.  Mas a visualização está lenta para carregar.
A visualização tipo mapa de calor não funcionou.

**Comment by sauloantuness** [comment]
@waltersf a visualização tipo mapa de calor foi corrigida no PR #64.

A issue está aberta devido ao tempo de carregamento?

**Comment by waltersf** [comment]
Fixed
