### ISSUE TITLE
Adicionar a biblioteca modin

### ISSUE THREAD

**Issue by zilton** [eubr-bigsea/citrus#188]
Seria interessante adicionar a biblioteca modin ao requirements do LEMONADE.

Como demonstrado no link abaixo, torna a leitura de dados extremamente mais rápida e eficiente do que com o pandas nativo.

[Link](https://towardsdatascience.com/get-faster-pandas-with-modin-even-on-your-laptops-b527a2eeda74)

Bastaria modificar apenas uma linha de código, o import do pandas, ficaria:

`import modin.pandas as pd`

**Comment by waltersf** [comment]
Done by @lucasmsp
