### ISSUE TITLE
Limpar o filtro de pesquisa

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#19]
1) Fiz um filtro para buscar um fluxo de dados
![image](https://user-images.githubusercontent.com/13971769/52122130-0ad80080-2609-11e9-96ae-7a2003ab392b.png)
2) Mas ao atualizar esta página ou clicar no menu Fluxo de trabalho o filtro permanece.

**Comment by waltersf** [comment]
A intenção é que o filtro permaneça mesmo entre diferentes requisições. Por exemplo, há momentos que você quer buscar só um padrão ou uma plataforma. Caso queira limpara o filtro, há o botão para essa finalidade.
