### ISSUE TITLE
Attributes are not being loaded

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#197]
Hi, 

the same issue is happening again in the workflow **1170**.

The attributes are not appearing in the "Available Attributes" box:

![image](https://user-images.githubusercontent.com/24958541/83981954-ea087500-a8f8-11ea-9672-147667ccefae.png)

This happens in the operation "Filter by function".

**Comment by alexgcsa** [comment]
Similar issue on the workflow 1217.

**Comment by waltersf** [comment]
I fixed the bug and deployed a new version. Check if it is ok. If so, please close this issue. 
Please, test if the option to retrieve you password is working. GMail was blocking the emails sent from Lemonade.

**Comment by alexgcsa** [comment]
It worked.

**Comment by alexgcsa** [comment]
Hi,

This is happening again when the students are trying to connect the output of **K-Means** with a **Scatter plot**. 

I have tried to replicate the issue here and the behavior is the same (workflow 1886):

![image](https://user-images.githubusercontent.com/24958541/84787255-27899400-afc4-11ea-94ed-200cdb691772.png)

I have just tried to set the names manually, and it worked on the workflow (id 1885). But a student tried it, and it didn't work for him. His workflow has the ID 1876.

Thanks.

Alex

**Comment by alexgcsa** [comment]
This was also an issue for the workflow 1815, but the student -- who was working on it -- managed the situation by using a **Save data** operation to save the results of K-Means as a dataset. So, he used it as an input to **Scatter plot**.

**Comment by waltersf** [comment]
Please, refresh the page. Configuration was incorrect in the app.lemonade environment (the problem was not occurring in other environments and it was difficult to identify the causes).

**Comment by alexgcsa** [comment]
It worked!

Thanks a lot.
