### ISSUE TITLE
Clicar duas vezes em uma operação na área de execução aparece um popup vermelho.

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#20]
Ao clicar duas vezes em uma operação na área de execução aparece um popup vermelho com informações irrelevantes para o usuário.

![image](https://user-images.githubusercontent.com/13971769/52122475-47582c00-260a-11e9-86c8-f1de13b6280f.png)

**Comment by waltersf** [comment]
Está sendo modificado. Mostrará informações sobre a tarefa.

**Comment by waltersf** [comment]
Popup removido
