### ISSUE TITLE
Problema na leitura da base ENEM

### ISSUE THREAD

**Issue by wallacemp** [eubr-bigsea/citrus#201]
Ao montar o fluxo de trabalho, quando vou configurar a caixa Agrupar linhas por
função, a opção DEPENDENCIA_ADMINISTRATIVA não aparece. O ponto é que nenhum atributo da planilha aparece para ser selecionada, embora tenha executados todos os passos constantes no PDF: Prática LEMONADE: Planejamento da solução. Então não sei se está ocorrendo algum problema de instabilidade no sistema, ou se estou cometendo algum erro que não percebi. 

![image](https://user-images.githubusercontent.com/34964322/84428559-0eb46380-abfd-11ea-878f-8f736ed6139e.png)

**Comment by waltersf** [comment]
Seu fluxo está vazio. Para identificar o problema, precisava que ele estivesse preenchido com as tarefas.
