### ISSUE TITLE
Metric on Evaluate Model

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#203]
Hi,

A student reported that her workflows (ids  1662 and 1667) were producing an error. This is due to the fact that she has not selected the metric used to evaluate the workflow.

The selection of this metric is currently optional. So, the user does not have to set it. But if he/she/* doesn't do it, LEMONADE will produce an error, such as:

![image](https://user-images.githubusercontent.com/24958541/84580898-fa659780-adb1-11ea-9641-c482f3b1b45b.png)

It would be interesting to have a default value to the metric. Transforming the **Metric to evaluation** into a mandatory field would be another option here.

Thanks in advance.

Alex de Sá

**Comment by alexgcsa** [comment]
Hi @lucasmsp,

was this changed done on app.lemonade?

I tested here again. The same error occurred. 

![image](https://user-images.githubusercontent.com/24958541/87572805-777e7800-c6a2-11ea-9d80-b1b16ae1022d.png)


Therefore, I will reopen the issue.

Alex

**Comment by waltersf** [comment]
It is not deployed yet. I'll deploy it today later.

**Comment by alexgcsa** [comment]
Alright, @waltersf.

I was not aware of it.

Thanks,

Alex

**Comment by alexgcsa** [comment]
Thank you, @waltersf and @lucasmsp .

I checked here and it's fine :)

Alex
