### ISSUE TITLE
Output - Feature Disassembler

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#207]
Hi,

I am trying to use the output of the **Feature Disassembler** operation, but it seems it is not visible for the next operations.

I could only use when I typed the name of the attributes.

Is it possible to check it?

This issue occurred in the workflow #2262.

Cheers,

Alex de Sá

**Comment by lucasmsp** [comment]
The "Top N" parameter in Feature Disassembler operation is now required in order to Lemonade predicts the column's output name.

**Comment by alexgcsa** [comment]
Thank you, @lucasmsp.

I will close the issue then as this enhancement was already done.

Alex
