### ISSUE TITLE
Converter categórico para numerico 

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#21]
A operação Converter Categórico para Numerico apenas funciona se utilizar o Vetorizar Atributo (Definidor de feature)

**Comment by waltersf** [comment]
@karenstemartins Poderia me dar mais detalhes? Qual fluxo acontece isto?

**Comment by karenstemartins** [comment]
Fluxo 41

**Comment by waltersf** [comment]
Será preciso rever esta operação. O nome anterior, Feature Indexer, representava melhor o que ela fazia: para categóricos, era possível criar um índice numérico para eles, para números, criava uma representação vetorial. Com o nome atual, não faz sentido usar a parte de vetores.

**Comment by waltersf** [comment]
Para referência
https://spark.apache.org/docs/2.4.0/api/python/pyspark.ml.html#pyspark.ml.feature.VectorIndexer
https://spark.apache.org/docs/2.4.0/api/python/pyspark.ml.html#pyspark.ml.feature.StringIndexer

**Comment by zilton** [comment]
Concluido.

Posteriormente o Walter coloca em produção.
