### ISSUE TITLE
Sumário estatístico

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#22]
Fluxo 46, 
1) Inseri o Fluxo para o sumário estatístico:
![image](https://user-images.githubusercontent.com/13971769/52123256-b0d93a00-260c-11e9-8d0e-b73f16f70635.png)
2) Ao executar o fluxo, da erro de **Valor obrigatório ausente**, mas não tem nenhum atributo a ser preenchido. O campo **Atributos (vazio=todos)** está vazio, logo deve considerar todos.
![image](https://user-images.githubusercontent.com/13971769/52123339-fb5ab680-260c-11e9-9237-d5d2f2110899.png)

**Comment by waltersf** [comment]
Corrigido. Outras operações poderão ter este mesmo problema. Vou deixar assim para que possamos identificá-las e corrigir a configuração.
