### ISSUE TITLE
Transformar valores por função: duplo clique não funciona mais

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#223]
O recurso de "Transformar valores por função", que na versão atual traz a lista das funções disponíveis, requer que toda a expressão seja digitada, não mais funcionando dar duplo clique no nome do atributo (nem no nome da função).

![image](https://user-images.githubusercontent.com/83472072/116742163-60a8d800-a9cd-11eb-917c-ecc1ac235ea0.png)

**Comment by waltersf** [comment]
Implementado no Citrus.
