### ISSUE TITLE
Após Intervalar, nomes dos atributos não mais aparecem nas listas e Join não permite digitar nome de atributo ausente na lista

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#224]
Seguindo-se o fluxo a partir do primeiro bloco de leitura, os atributos não são mais listados a partir do primeiro bloco de Intervalar. Esse fluxo foi construído a partir de uma importação de outro da versão app, em que o mesmo problema ocorreu. Mas, na nova versão esbarrou-se em outra dificuldade. O último bloco de Join que aparece no fluxo requer como chave um atributo que não mais é listado (o codmunres). Na versão app foi possível digitar o nome desse campo, mas esse recurso não está mais disponível para os blocos de Join na versão md.

O fluxo na versão md é o:
https://md.lemonade.org.br/#/workflows/1/580

O original na versão app é o:
https://app.lemonade.org.br/#/workflows/1/2454

**Comment by waltersf** [comment]
See #233

**Comment by waltersf** [comment]
Fixed
