### ISSUE TITLE
Operação Junção: Tipo Junção está retornando automaticamente para o default (INNER JOIN)

### ISSUE THREAD

**Issue by iagoadvaz** [eubr-bigsea/citrus#232]
Ao utilizar outros tipos de junção, como o Right Outer Join, a operação está retornando automaticamente para o tipo default, como ilustrado nas imagens abaixo:

1. A operação é inserida utilizando Right Outer Join:
![1](https://user-images.githubusercontent.com/19698177/117682316-4fa85580-b189-11eb-917c-45d1573aee9a.png)

2. Ao executar o fluxo, a opção escolhida não é refletida no código fonte gerado:
![2](https://user-images.githubusercontent.com/19698177/117682482-7d8d9a00-b189-11eb-819f-f2936f9faafa.png)

3. Após execução do fluxo, a operação passa a mostrar o tipo de junção default:
![3](https://user-images.githubusercontent.com/19698177/117682578-98f8a500-b189-11eb-956b-5aef08b82937.png)

**Comment by waltersf** [comment]
@iagoadvaz No ambiente md está corrigido. Devo implantar em breve no outro ambiente.

**Comment by iagoadvaz** [comment]
Obrigado @waltersf , aguardo retorno para realizar os teste.
