### ISSUE TITLE
Volta do problema de entradas trocadas na Junção

### ISSUE THREAD

**Issue by jufs128** [eubr-bigsea/citrus#238]
Testando um fluxo, na seleção de atributos estavam aparecendo os da entrada 2 sob "Entrada 1" e os da entrada 1 sob "Entrada 2". O fluxo foi importado, então na bloco da função estava correto, mas se clico em "Escolher uma opção ..." os atributos estão trocados.

![image](https://user-images.githubusercontent.com/42375312/121914592-c98fa980-cd08-11eb-827a-c85ee7377129.png)
![image](https://user-images.githubusercontent.com/42375312/121914673-dd3b1000-cd08-11eb-8053-7100ce6b7cfd.png)

**Comment by waltersf** [comment]
Poderia informar qual é o ambiente e qual é o fluxo que você está usando? Se foi um fluxo importado, poderia desconectar as entradas que chegam à operação Join e reconectá-las?

**Comment by jufs128** [comment]
Já tentei reconectá-las e até testei em outro fluxo e deu o mesmo erro... Estranhamente só pra mim porque falei pro Eduardo e nos dele está tudo normal.

O fluxo é o 742, chama MM_CausasBas_BR

**Comment by helenapato** [comment]
Estou com o mesmo problema na versão md do Lemonade. No menu dropdown que aparece para selecionar as condições da junção, aparecem os atributos das bases trocadas. Montei o fluxo do zero, seu número é 1103. Para contornar isso é possível digitar manualmente os nomes dos atributos corretos nos campos, mas acredito que seja preferível usar o menu dropdown, que é mais intuitivo.

Abaixo temos os atributos da base 1, que chequei com a operação “selecionar atributos”.

![image](https://user-images.githubusercontent.com/42720360/133079091-d456e935-00c2-4e7a-a3df-2d4a02d52235.png)

Então podemos ver a base 1 ligada à entrada 2 da operação de junção.

![image](https://user-images.githubusercontent.com/42720360/133079120-4cc585e6-4489-4a9a-a1cb-259e7ba9e23a.png)

Porém, quando clico para escolher o atributo correspondente da entrada 2 para fazer a junção, aparecem os atributos da base que está na entrada 1, a base 2.

![image](https://user-images.githubusercontent.com/42720360/133079183-afd29261-48da-4009-9848-fe865f81a2ca.png)

E quando clico para escolher o atributo correspondente da entrada 1 para fazer a junção, aparecem os atributos da base que está na entrada 2, a base 1.

![image](https://user-images.githubusercontent.com/42720360/133079217-e8d5cfa5-e50d-4679-a2f2-4d240a2a5d59.png)

Se escolho de acordo com o menu dropdown recebo o seguinte erro de execução:

pyspark.sql.utils.AnalysisException: 'Cannot resolve column name "cod_regiao" among (estado_cod, estado_sigla, estado_nome, regiao_cod);'

Que indica que a operação está procurando o atributo da base 1 cod_regiao no meio dos atributos da base 2. Isso é válido para todas as operações de junção do fluxo (são 4).

**Comment by waltersf** [comment]
Problema relacionado à ordenação em Javascript. Aparentemente, o código funcionava algumas vezes no Chrome para Windows.
