### ISSUE TITLE
Sugestão: Acrescentar count(distinct ...) ao rol de funções da operação "Agrupar linhas por função"

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#239]
Se possível, acrescentar algo similar a count(distinct ...) ao rol de funções da operação "Agrupar linhas por função". Há a opção 'Count', mas sem a cláusula distinct (ver figura).

Por ora, tem sido possível realizar a operação desejada utilizando-se query SQL (select classe, count(distinct id) as contagem from ds1 group by classe order by contagem desc) ou combinações de operações "Agrupar linhas por função" (com collect_set) e SQL (select classe, size(result_collect) as contagem from ds1).

A ideia seria oferecer uma forma mais direta e simples para o usuário. Talvez tenha outra estratégia que eu não tenha pensado.

![image](https://user-images.githubusercontent.com/83472072/122064172-50a35700-cdc7-11eb-9c65-5cbeba7d2108.png)

**Comment by waltersf** [comment]
Adicionadas as funções count_distinct, sum_distinct, stddev, stddev_pop, variance, variance_pop, kurtosis e skewness.
