### ISSUE TITLE
Base de dados Airplane_Crashes_and_Fatalities_Since_1908

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#24]
Apesar da base funcionar na Pré-visualização, na operação Ler dados do fluxo 48, os dados são reconhecidos como null.
![base](https://user-images.githubusercontent.com/8696951/52125359-60b1a600-2613-11e9-85bc-d571ef6052cd.png)
![tabela](https://user-images.githubusercontent.com/8696951/52125367-64ddc380-2613-11e9-8cbf-53038429cd34.png)

**Comment by waltersf** [comment]
Provavelmente, problema com o formato de data. Usamos duas coisas diferentes nesse caso. Data sempre é um problema. Mudei lá para CHARACTER. Teria que ter alguma forma de especificar o formato. O Spark só aceita ISO por default aaaa-mm-ddTHH:MM:SS

**Comment by waltersf** [comment]
Adicionei suporte à especificação do formato para datas.
