### ISSUE TITLE
Erro ao fazer junção e agrupamento

### ISSUE THREAD

**Issue by victorcaet** [eubr-bigsea/citrus#245]
Estou tendo um erro ao tentar fazer uma junção de um dataframe com o mesmo dataframe após selecionar duas colunas e agrupar por uma delas.
O erro apresentado é unhandled error.
A parte que consegui entender que faz mais sentido na descrição do erro é essa:
pyspark.sql.utils.AnalysisException
'Resolved attribute(s) <nome_atributos> missing from <nomes_atributos> in operator 
!Project <lista_de_atributos>

Fiz um workflow toy para isolar esse problema:
![workflow_20](https://user-images.githubusercontent.com/23336477/124005985-15e91380-d9b0-11eb-8f05-9895275ea3be.png)

**Comment by educsantos** [comment]
Reproduzi um fluxo similar ao postado pelo Victor. Deu erro sobre Spark. Sobre Scikit-learn, não.

Spark:
https://md.lemonade.org.br/#/jobs/1/9808 

Scikit:
https://md.lemonade.org.br/#/jobs/4/9809

**Comment by wagnermeirajr** [comment]
Obrigado Eduardo.

Victor, pode confirmar que o erro observado pelo Eduardo é o que você teve também?

**Comment by victorcaet** [comment]
@wagnermeirajr Eu não tenho acesso a esse ambiente, eu rodo pelo projeto do MP.
Parece ser o mesmo erro, lá roda com Spark mesmo.
Testei novamente fazendo duas operações de leitura e funcionou.

**Comment by wagnermeirajr** [comment]
Me parece ser um erro localizado. Victor, se você já puder fazer essa alteração (ler a base duas vezes) para continuar trabalhando, por favor faça enquanto o erro é corrigido.

**Comment by waltersf** [comment]
Relacionado ao bug do Spark https://issues.apache.org/jira/browse/SPARK-14948

**Comment by waltersf** [comment]
Fiz uma correção no Lemonade, agora self-join é permitido usando a mesma entrada. Tive que usar alias(), como descrito em https://sparkbyexamples.com/pyspark/pyspark-sql-self-join-with-example/
