### ISSUE TITLE
Sugestão: desvincular o nome do bloco do identificador do mesmo

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#248]
Essa sugestão partiu do professor Leonardo Oliveira. Ele percebeu que, para evitar dúvidas de usuários de áreas distintas da área de computação, seria interessante que não houvesse a restrição de os nomes visualizados nos blocos terem que ser distintos. Alguns alunos não compreendem que o erro foi esse ao ler o log.

Didaticamente, seria interessante permitir dois blocos com o mesmo nome "Gera tabela", por exemplo, uma vez que as próprias linhas do fluxo deixaria claro para usuário a tabela a ser gerada em cada caso.

A sugestão seria que o identificador de cada operação seja interno (talvez permitindo a edição para eventuais ajustes manuais que se fazerem necessários), deixando o campo de nome do bloco para livre edição.

**Comment by waltersf** [comment]
@educsantos Poderia testar por favor. Acho que esta opção já foi tratada na versão 2.1.0

**Comment by educsantos** [comment]
Continua sim. Na figura abaixo, duas caixas com o mesmo nome ocasionaram erro. 

![image](https://user-images.githubusercontent.com/83472072/145442609-45272f19-86e8-4819-94ca-fe421007dd3c.png)

Esse exemplo foi só para ilustrar mesmo (originalmente, tínhamos uma caixa com nome "Aprovados" e outra com o nome "Reprovados", em vez de duas com o nome "Resultado).

**Comment by waltersf** [comment]
Fixed
