### ISSUE TITLE
Sometimes, Lemonade is not executing workflows

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#25]
Not sure if the Lemonade's system is overloaded or if there is another reason, but sometimes it takes too long to run a simple workflow (id 52), such as the one in the following figure:

![image](https://user-images.githubusercontent.com/24958541/52165869-67145080-26ed-11e9-8a1b-75f36fd73aec.png)

**Comment by alexgcsa** [comment]
The status 'Running' remains and Lemonade does not complete the task (even to show an error)...

**Comment by waltersf** [comment]
There was an error in flow: it was using an attribute "Class", with capital C, but the correct one is "class". I added a condition to handle this and display a user-friendly message.
