### ISSUE TITLE
Dashboard - Não há opção de excluir dashboard

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#250]
Ao testar a função de dashboard não consegui encontrar nenhuma opção para excluir o dashboard publicado. Essa opção existe para bases de dados e para fluxos de trabalho, seria interessante que um dashboard também pudesse ser excluído.

![image](https://user-images.githubusercontent.com/42720360/127164254-5ac4ccbf-9a10-414d-84cd-875693d300ca.png)

![image](https://user-images.githubusercontent.com/42720360/127164698-f3a269c1-cd32-455d-ae27-32666436f761.png)

**Comment by waltersf** [comment]
Adicionada a opção de exclusão
