### ISSUE TITLE
Dashboard - Opção Adicionar Texto Markdown gera erro

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#251]
Quando clico na opção adicionar texto markdown em um dashboard recebo um erro sem explicações.

![image](https://user-images.githubusercontent.com/42720360/127165185-5c502533-7a70-4c72-8eb3-dbe433cc5c09.png)

**Comment by waltersf** [comment]
Corrigido

**Comment by helenapato** [comment]
Muito obrigada, verifiquei e está funcionando corretamente.
