### ISSUE TITLE
Dashboard - Botão de salvar não tem texto

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#252]
Cliquei neste botão sem nome para testar seu efeito e descobri que era o botão de salvar, mas deveria estar escrito isso nele.

![image](https://user-images.githubusercontent.com/42720360/127165504-4bb5b6f7-862f-40c6-aa98-0a33d9f59341.png)

**Comment by waltersf** [comment]
Corrigido

**Comment by helenapato** [comment]
Muito obrigada, verifiquei e está mostrando corretamente.
