### ISSUE TITLE
Dashboard - Opção de tornar público sempre ativada

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#253]
Quando publicamos o dashboard no fluxo de trabalho, ele deveria ser privado por default. No dashboard podemos alterar essa configuração. Porém, o que está acontecendo é que um dashboard publicado de um fluxo já é público por default e qualquer outro usuário pode vê-lo e alterá-lo. Não consegui mudar a configuração, tornando-o privado. No caso do screenshot abaixo, mesmo com a opção de tornar público desativada, ele ainda é visível para os outros.

![image](https://user-images.githubusercontent.com/42720360/127165868-5b22868a-ee1e-4bb4-b7b5-e962f077c494.png)

**Comment by waltersf** [comment]
É como foi implementado. Todos os dashboards são visíveis para os usuários autenticados. A ideia aqui era permitir usuários não autenticados terem acesso ao dashboard.

**Comment by helenapato** [comment]
Entendo a parte de o dashboard estar visível para qualquer usuário, mas ele também pode ser editado por qualquer um, isso não seria um problema? Nesse caso gostaria de saber qual a utilidade da opção de tornar o dashboard público, se ele já é público por default.

**Comment by waltersf** [comment]
> Entendo a parte de o dashboard estar visível para qualquer usuário, mas ele também pode ser editado por qualquer um, isso não seria um problema? Nesse caso gostaria de saber qual a utilidade da opção de tornar o dashboard público, se ele já é público por default.

Seguinte:
Público: visível para qualquer pessoa com o link, mesmo que não seja usuária do Lemonade. Você poderia copiar o link e passá-lo para alguém fora. 
Não-público: Somente usuários do Lemonade (autenticados).

O que você sugere é uma permissão intermediária, de forma que só o dono ou quem for autorizado por ele possa ter acesso. 

Essa possibilidade existe, mas não tem como priorizá-la agora, pois não há quem possa implementá-la.

**Comment by waltersf** [comment]
Fixed
