### ISSUE TITLE
Cluster para o Scikit indefinidamente alocando recursos

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#256]
Criei fluxo contendo somente a leitura de dados sob a plataforma Scikit-Learn.
https://md.lemonade.org.br/#/workflows/4/1075

Ao executar, selecionei o Cluster apropriado (Sklearn cluster).

A execução permanece com "Job is allocating computer resources. Please wait".

Experimentei executar selecionando outros clusters. Também não funcionou.

**Comment by waltersf** [comment]
Era problema com a configuração do cluster. O token usado para criar o cluster era inválido. Está funcionando agora.
