### ISSUE TITLE
Download de bases no md dando erro

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#258]
Ocorreu com mais de uma base (inclusive com uma pertencente ao meu usuário).
E mesmo com base pequena.

Base aparece na listagem, pré-visualização ok, visualização de detalhes da base (nome, atributos etc.) também ok.

Mas ao tentar baixar a base, aparece o erro:
"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

![image](https://user-images.githubusercontent.com/83472072/129036651-a815c0ae-5d63-472a-86bb-b5e275e91a08.png)

**Comment by waltersf** [comment]
Erro de configuração (imagem desatualizada). Corrigi agora. Tenta novamente, por favor.

**Comment by educsantos** [comment]
Está ok. Obrigado.
