### ISSUE TITLE
Problema na operação Avaliar Modelo

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#262]
Versão do Lemonade: md

Não é possível adicionar mais de um atributo como preditor na operação "Avaliar Modelo". Como mostrado na imagem abaixo, a forma de selecionar atributos nesse campo é por meio de um menu dropdown, que só permite a escolha de um atributo por vez.

![image](https://user-images.githubusercontent.com/42720360/133078189-ea648ebe-6be6-4b32-93ea-35f42420d49e.png)

O fluxo original foi gerado na versão app e, ao importá-lo, o respectivo campo aparece com vários atributos (como mostrado abaixo), e a execução acontece corretamente. Porém, ao tentar montar o fluxo do zero, não foi possível selecionar mais de um atributo por vez.

![image](https://user-images.githubusercontent.com/42720360/133077141-23708af8-0827-48fe-a2dc-8a1ab7cb49ea.png)

Fluxo original (app): https://drive.google.com/file/d/1abgmVXKXCOg_QIWWoCDlG5uNEdae0eqk/view?usp=sharing

Issue similar: https://github.com/eubr-bigsea/citrus/issues/225

**Comment by waltersf** [comment]
Originalmente, esta operação aceitava realmente múltiplos atributos. Estava errado. No seu caso, você tem que escolher só um campo, cujo nome aparece na imagem e deve ser Valor_Predito. Talvez uma melhoria seja mudar o rótulo para algo mais claro, algo como "Atributo com a predição" (feito).  Basicamente, o avaliador compara esse atributo com o label e ambos tem multiplicidade 1.
