### ISSUE TITLE
Junção - Prefixos são sempre adicionados

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#263]
Versão do Lemonade: md

Na operação de junção, durante a montagem do fluxo, existe a opção de não colocar prefixos nos atributos que serão usados como condição da junção. Porém, durante a execução, eles são adicionados mesmo assim.

Abaixo está a minha configuração da primeira junção. Os campos dos prefixos estão vazios.

![image](https://user-images.githubusercontent.com/42720360/133255540-aef078b4-808a-4128-8e90-b51e804c0cec.png)

![image](https://user-images.githubusercontent.com/42720360/133255572-bc40f313-67c2-4a0f-b9a0-013126ba9b76.png)

Após a junção, coloquei uma operação de selecionar atributos para verificar seus nomes. Abaixo está sua configuração, usando os nomes dos atributos sem prefixo (que são os que aparecem para seleção quando, na operação de junção, escolho não usar prefixos).

![image](https://user-images.githubusercontent.com/42720360/133255610-3acf8140-2405-4121-bcae-91fb56d6ecc9.png)

Quando executo o fluxo recebo esse erro, que mostra que os prefixos foram adicionados mesmo sem eu configurá-los. O atributo estado_cod foi renomeado para ds1_estado_cod, assim como os demais atributos também receberam os prefixos.

![image](https://user-images.githubusercontent.com/42720360/133255629-f56dd9ce-16bc-4f4d-962f-9298c153c5a3.png)

Dessa forma, a opção de remover os prefixos não está funcionando corretamente. Como medida provisória, é melhor deixar os prefixos e lidar com eles durante o fluxo, porém é uma questão que poderia ser consertada.

**Comment by waltersf** [comment]
Corrigido
