### ISSUE TITLE
Problema na operação Intervalar

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#265]
Versão do Lemonade: md

Ao adicionar uma operação "Agrupar linhas por função" depois de uma operação "Intervalar", os atributos disponíveis não apareceram para serem selecionados. Para contornar esse problema, tive que digitá-los manualmente em seus respectivos campos. Abaixo está um exemplo.

Como as operações estão no fluxo

![image](https://user-images.githubusercontent.com/42720360/133257999-768f1e87-4e0c-45d6-8985-76fbeebb9c59.png)

Operação “Intervalar”

![image](https://user-images.githubusercontent.com/42720360/133258073-ac2489cd-91ae-4891-b0ff-97cf251f683a.png)

Operação “Agrupar linhas por função”. Ela aparece com os campos preenchidos pois digitei os atributos em seus respectivos campos manualmente.

![image](https://user-images.githubusercontent.com/42720360/133257562-74c20663-f229-4496-8efb-472dbfd0dd38.png)

Menu de seleção de atributos para agregação da operação “Agrupar linhas por função”. Nenhum atributo disponível é listado. Usei o campo "Não está na lista?" para adicionar o atributo.

![image](https://user-images.githubusercontent.com/42720360/133257586-3a12e662-2a0a-4ce6-96d1-cf3f82dbfaf1.png)

Menu de função de agregação da operação “Agrupar linhas por função”. Nenhum atributo disponível é listado. Digitei o nome do atributo no campo "Atributo".

![image](https://user-images.githubusercontent.com/42720360/133257616-ec954c67-8079-494f-86b3-5463c4b2e551.png)

Caso necessário, este é o fluxo número 1118.

Issue similar: https://github.com/eubr-bigsea/citrus/issues/224

**Comment by waltersf** [comment]
Corrigido. Faltava inserção na tabela operation_script com a regra para este caso.
