### ISSUE TITLE
Salvar modelo não sobrescreve mesmo quando essa opção está assinalada

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#268]
Isso já ocorria na versão app. Continua na versão md. 

A operação "Salvar modelo" tem uma propriedade "Ação caso modelo já exista" com duas opções: "Sobrescrever" ou "Gerar erro". 

Mesmo assinalando "Sobrescrever", a execução não sobrescreve - gera outro com o mesmo nome. Assim, caso tenha havido alguma atualização no modelo, o usuário deve estar atento para selecionar o último (de maior id) ao configurar a operação "Carregar modelo".

**Comment by waltersf** [comment]
Corrigido
