### ISSUE TITLE
Gráfico da Curva ROC não está sendo gerado corretamente.

### ISSUE THREAD

**Issue by wagnermeirajr** [eubr-bigsea/citrus#269]
![image](https://user-images.githubusercontent.com/14075212/135260653-6205f9e4-084d-47fc-b0fb-e89d225f880a.png)

Independente do valor do AUC, a curva ROC é sempre a mesma, e parece ser perfeita.

**Comment by wagnermeirajr** [comment]
E quando deveria ser perfeita, não é!

![image](https://user-images.githubusercontent.com/14075212/135262377-d544d9fe-5514-491c-a932-3842668449dd.png)

**Comment by waltersf** [comment]
A geração do gráfico está usando o atributo errado. Deveria usar a coluna probability (probabilidade da predição), mas está usando o atributo escolhido como prediction diretamente.
