### ISSUE TITLE
Workflow copy

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#27]
It would be nice to have the option to copy an workflow. This would avoid double work in some cases.

**Comment by waltersf** [comment]
In workflow editor, you can save a copy in option "Save As..."

**Comment by alexgcsa** [comment]
At the begging, my recommendation was to do that in the workflow page:


![image](https://user-images.githubusercontent.com/24958541/52176319-42c17e00-2798-11e9-90bf-41dd5a78540d.png)

Instead of just having the action 'delete', it should also have the option 'copy'.  I believe it would be more intuitive because 'saving as' and 'copy' are different things.  But we can discuss latter, anyway.

I tried to use the option 'Saving as' and it doesn't work. I'm going to open an issue.
