### ISSUE TITLE
Características da árvore de decisão deixam de ser mostradas de forma aleatória

### ISSUE THREAD

**Issue by wagnermeirajr** [eubr-bigsea/citrus#270]
Na instância md.lemonade.org.br, fluxo 1110, execução 10640, as características da árvore são mostradas. Habilitei então a amostra da saída da partição, e na execução 10641 parou de ser gerada, assim como nas execuções seguintes: 10642 e 10643. Quando alterei a profundidade máxima da árvore para 3, as características voltaram a ser mostradas: 10644.

**Comment by waltersf** [comment]
Bug relacionado à forma como a execução anterior de uma tarefa é "reaproveitada" caso não haja nenhuma alteração (uso de cache). O cache não inclui dados relacionados à resultados dos algoritmos (gráficos e textuais), mantendo apenas os dataframes de saída. Possível solução: manter os resultados dos algoritmos no cache.
