### ISSUE TITLE
Adicionar "Full outer" na operação de Junção

### ISSUE THREAD

**Issue by LucasLage** [eubr-bigsea/citrus#274]
No operador Lemonade "Junção", precisamos que seja adicionado o Tipo de Junção "Full outer".
O "full outer join" é a junção do "left outer" com o "right outer".
Exemplo do full outer no spark
https://sparkbyexamples.com/spark/spark-sql-dataframe-join/#sql-full-outer-join

**Comment by waltersf** [comment]
Fixed in Citrus.
