### ISSUE TITLE
Junção invertendo as entradas - versão md

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#275]
Inicialmente, imaginei que era apenas o mesmo problema, corrigido há algum tempo, em que o Lemonade não respeitava o que estava conectado à Entrada_1 e Entrada_2. Mas, percebi que o comportamento é diferente agora. Antes, bastava inverter as conexões das entradas, respeitando o que fora determinado pelo Lemonade. Mas agora, ao fazer isso, e abrir novamente as propriedades do bloco, percebe-se que a determinação do que é Entrada_1 e do que é Entrada_2 também é invertida.

O problema ocorreu tanto para um fluxo importado (de outro usuário, da própria versão md), como também em um fluxo que construí do zero e fui executando a cada operação. Ocorreu erro mesmo tendo apenas duas leituras e uma join para combiná-las. Eu queria usar a seleção de atributos da própria Join, mas não funcionou. Por isso, usei os prefixos. Mas, como ilustrado abaixo, há algo confuso quanto às formas em que os atributos estão sendo associados às entradas.

As quatro primeiras imagens abaixo mostram as bases conectadas às entradas da Join. Temos NV na Entrada_1 e MI na Entrada_2. (Observe os nomes das bases e seus respectivos atributos, além da forma que foram conectadas à Join.)

![image](https://user-images.githubusercontent.com/83472072/137776547-918ad56f-cbe2-41f6-b216-2a20acaf496a.png)

![image](https://user-images.githubusercontent.com/83472072/137776619-c65079e0-fd8d-4a67-b7e6-a3db1b03d602.png)

![image](https://user-images.githubusercontent.com/83472072/137783128-865f0f5b-5fbe-4a39-8ca2-5dd262bb8731.png)

![image](https://user-images.githubusercontent.com/83472072/137783289-e15f4767-36ee-4222-b10a-d03405cf8e26.png)

Na imagem seguinte, percebe-se que os prefixos 'nv_' e 'mi_' foram atribuídos à Entrada_1 e à Entrada_2 respectivamente, conforme esperado.

![image](https://user-images.githubusercontent.com/83472072/137777100-4d3f2e58-96be-406d-8153-c382eeefe678.png)

Entretanto, vê-se nas duas imagens seguintes, que os atributos listados para a Entrada_1 e para a Entrada_2 aparecem invertidos (o mesmo ocorre ao visualizá-los do lado direito da janela - marcando "Selecionar atributos"). 

![image](https://user-images.githubusercontent.com/83472072/137780405-ecf75287-b01a-47fa-892e-81e2fb248264.png)

![image](https://user-images.githubusercontent.com/83472072/137780490-13f193c3-2993-4958-8d91-0652bc3a62ff.png)

O problema parece ser ainda pior. Perceba-se que se as informações das duas janelas acima estivessem corretas deveríamos ter, na saída da join, os atributos "nv_a2008", "nv_total", "mi_casos_total", "mi_prprenat7plus" (o que já seria estranho, pois teríamos os atributos da base de MI com o prefixo nv_ e os atributos da base NV com o prefixo mi_). Entretanto, deixando-se como está, percebe-se que os prefixos foram designados corretamente para os atributos, conforme mostra a lista de atributos da caixa de operação "Transformar valores" adicionada à saída da join (figura abaixo).

![image](https://user-images.githubusercontent.com/83472072/137781779-1a9da226-a819-4d7a-aad0-89fa45a4e3fe.png)

Emfim, ocorre erro se utilizo a opção "Selecionar atributos" da configuração da join e só consigo ir adiante, configurando os prefixos de forma inversa do que eu faria.

**Comment by waltersf** [comment]
Duplicated #238
