### ISSUE TITLE
Versão md: Lista de "Carregar modelo" não exibe o modelo que preciso selecionar

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#287]
A lista para selecionar o modelo a ser carregado mostra sempre as mesmas 4 páginas contendo 5 modelos, cada uma. Não renova a lista exibindo modelos que salvei mais recentemente. O uso do Filtro também não resolve porque só faz a filtragem entre os 20 listados. Todas as execuções foram feitas com o mesmo usuário.

Como exibe a mensagem "Exibindo registros de 1 até 5, para um total de 20 registros" e não recebi erro ao salvar o modelo em outro fluxo, estou supondo que o problema seja apenas que o modelo que preciso não está aparecendo na listagem.

O modelo que preciso é o idsus_nivel_1, salvo pelo fluxo 1333.
Em outro fluxo, precisarei carregar também o modelo idsus_nivel_2, salvo pelo fluxo 1334.

Seguem abaixo, as imagens mostrando toda a minha listagem de modelos disponíveis quando tento carregar o modelo no fluxo 1358.

![lista_modelos_1](https://user-images.githubusercontent.com/83472072/145029090-e97a3039-5744-4d55-87a3-5048858acccb.png)

![lista_modelos_2](https://user-images.githubusercontent.com/83472072/145029173-6020f6e9-2feb-448e-8f95-6ef5b2624a35.png)

![lista_modelos_3](https://user-images.githubusercontent.com/83472072/145029198-c5fda025-c863-4502-a72b-24ecb376a359.png)

![lista_modelos_4](https://user-images.githubusercontent.com/83472072/145029232-8db5c480-5457-4e85-a899-dee2be608999.png)

**Comment by waltersf** [comment]
Corrigido
