### ISSUE TITLE
Versão md: gráfico de barras só com barras verticais

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#290]
A caixa para gráfico de barras apresenta o parâmetro "Modo de exibição" com as opções:

- Barras verticais
- Barras horizontais
- Barras verticais empilhadas
- Barras horizontais empilhadas

Mas o gráfico é sempre construído com "Barras verticais" não importando a opção selecionada.

**Comment by waltersf** [comment]
Corrigido
