### ISSUE TITLE
versão md - spark: Random Forest Regressor dando erro por reclamar a ausência de dois argumentos 'features_col' e 'features'

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#291]
Erro:
TypeError: __init__() missing 2 required positional arguments: 'features_col' and 'features'

Fluxos:

https://md.lemonade.org.br/#/workflows/1/596
e
https://md.lemonade.org.br/#/workflows/1/1519

Este último foi construído seguindo-se a documentação do próprio Lemonade.

**Comment by waltersf** [comment]
Fixed
