### ISSUE TITLE
Função map_keys aparece listada, mas durante a execução gera erro "não existe"

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#292]
Versão do Lemonade: md

Estava explorando as funções do Lemonade e tentei usar a função map_keys, que aparece listada nas funções de referência, dentro da operação 'Transformar Valores por Função'. Porém, durante a execução, recebi um erro que dizia que a função não existia.

Função listada:

![image](https://user-images.githubusercontent.com/42720360/146797207-da6b4856-7cf7-4c0d-a998-427b74335860.png)

Erro na execução:

![image](https://user-images.githubusercontent.com/42720360/146797329-bf25cb9b-77b1-483a-b71c-e006a78f827e.png)

**Comment by waltersf** [comment]
Outra função que foi reportada não existir: flatten.

**Comment by waltersf** [comment]
Corrigido. @helenapato, alguma outra função que tenha notado que esteja faltando?

**Comment by waltersf** [comment]
Fixed

**Comment by helenapato** [comment]
> Corrigido. @helenapato, alguma outra função que tenha notado que esteja faltando?

Por enquanto não, se encontrar aviso. Muito obrigada.
