### ISSUE TITLE
Atributos não estão sendo carregados

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#30]
Após conectar com o Ler dados, os atributos da base não aparecem.

![atributos](https://user-images.githubusercontent.com/8696951/52167317-7cdf4100-2700-11e9-8e72-379026df0897.png)

**Comment by waltersf** [comment]
Por favor, informe o número do fluxo.

**Comment by karenstemartins** [comment]
51 e 54, mas após executar pela primeira vez os atributos foram carregados.

**Comment by waltersf** [comment]
Could not reproduce. Latest update may have fixed it.
