### ISSUE TITLE
Opções do Filtrar por função

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#31]
O campo "Expressão para filtro" não deveria ser obrigatório, pois ele funciona sem ser preenchido.

![image](https://user-images.githubusercontent.com/8696951/52167391-74d3d100-2701-11e9-9dce-f55300b987fd.png)

O campo está em inglês (Filtro)
![image](https://user-images.githubusercontent.com/8696951/52167416-c1b7a780-2701-11e9-96da-5eff028ddbc3.png)

**Comment by waltersf** [comment]
O campo Filtro foi removido. Há uma melhoria a ser feita (não exibir a caixa pedindo o alias).

**Comment by waltersf** [comment]
Filtro removido, campo alias aparece somente se for pertinente.
