### ISSUE TITLE
md: leitura de base muito demorada

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#318]
Versão no md, fluxo com apenas leitura de uma base com apenas duas colunas e cinco linhas (já bastante utilizada - regioes.csv), demorando muito ou executando indefinidamente.

- Sem exibir amostra, a leitura se completou com 42.80s.

- Com a opção para "exibir amostra" marcada, está rodando indefinidamente.

O problema ocorreu com outras bases também não muito grandes, utilizei essa outra e em um novo workflow (só com a operação de leitura) para fins de teste.

**Comment by waltersf** [comment]
Não é necessariamente um bug. É um problema com o ambiente. Nesses casos, melhor entrar em contato pelo grupo.
