### ISSUE TITLE
Estudar VUE.JS (2.7.x)

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citrus#320]
Especificamente, a versão 2.7.x, que ainda é usada pelo projeto. Mas estudar a "composition API" que é a nova forma de se utilizar VueJS, para uma possível conversão no futuro.

**Comment by Luiz20hdsg** [comment]
Conteúdos do Vue.js estudados até o momento: Componentes , Class e Style Bindings, List Rendering , Attribute Binding , Conditional Rendering e Event Handling.
