### ISSUE TITLE
'Saving as' is not working

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#33]
The option '_Saving as_' into the workflow is not working on Firefox.

Besides, into '_Saving as_', just the sub-option _'As a image (a download window will appear)_' works on Google Chrome. The remaining sub-options ('_New name (a copy of the workflow will be created, but not loaded)_ ' and '_As a template workflow_') are not working at all.

**Comment by waltersf** [comment]
"Save as a copy" is working now. Save as Image will require more tests to work in FF.

**Comment by waltersf** [comment]
Removed the option "Save as template" because it was not implemented yet. Fixed save as and save as image. Please, test and if it is ok, close this issue. Remember to refresh browser when a issue is closed because JS may be outdated.

**Comment by alexgcsa** [comment]
It works.
