### ISSUE TITLE
Operação de Agrupar linhas por função

### ISSUE THREAD

**Issue by barbarasilveiraf** [eubr-bigsea/citrus#34]
Os atributos da operação Agrupar linhas por função fazem referência ao nome antigo, agregação.
Sugiro mudar para agrupar.

![image](https://user-images.githubusercontent.com/13971769/52176608-26bfdb80-279c-11e9-84ac-7c56c76f65a3.png)

**Comment by waltersf** [comment]
Feito.

**Comment by alexgcsa** [comment]
@karenmartins, teste

**Comment by alexgcsa** [comment]
@karenstemartins, você poderia testar?

Att.,

Alex

**Comment by karenstemartins** [comment]
A descrição está da seguinte forma: "Realiza a agregação de dados agrupados por um conjunto de atributos". 

Acho que vale a pena mudar para "Realiza agrupamento dos dados por um conjunto de atributos".

o que você acha @alexgcsa ?

**Comment by alexgcsa** [comment]
Ok quanto ao novo texto, @karenstemartins .

Att.,

Alex

**Comment by alexgcsa** [comment]
@zilton , você poderia dar uma olhada nessa sugestão da @karenstemartins ?

**Comment by waltersf** [comment]
Corrigido
