### ISSUE TITLE
Escalador Padrão (Z-score) não funciona sem o Definidor de Feature

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#36]
Fluxo 61

![image](https://user-images.githubusercontent.com/8696951/52208824-0c076880-2869-11e9-9d3b-91d2cd19c33b.png)

**Comment by waltersf** [comment]
Em desenvolvimento

**Comment by waltersf** [comment]
Corrigido. Se possível, teste com outros escaladores (ex. min-max)
