### ISSUE TITLE
Edit storage screen doesn't show main url

### ISSUE THREAD

**Issue by lucasmsp** [eubr-bigsea/citrus#417]
The edit storage screen (administration > storage > edit storage) doesn't show the "main url" parameter even if the content is available in database.

![image](https://github.com/eubr-bigsea/citrus/assets/11474962/9afd39e4-d16d-4080-a55a-63fe1f50e84a)

**Comment by waltersf** [comment]
Fixed. Please, rebuild the **limonero** project
