### ISSUE TITLE
Vincular workflow à etapa da Pipeline

### ISSUE THREAD

**Issue by rfalexandre** [eubr-bigsea/citrus#423]
Duas questões estão ocorrendo ao tentar associar um workflow à etapa da Pepiline:

1. Não é possível vincular um workflow do "tipo experimento SQL".
2. Ao vincular um workflow (do tipo workflow), o registro aparentemente é armazenado. No entanto. ao retorna na mesma tela para um eventual ajuste, o workflow já associado não está sendo exibido. Em resumo, não mantém o registro no "dropdown".

**Comment by waltersf** [comment]
Corrigido. Gentileza testar, reportar se ainda há erros ou fechar a issue se tudo ok
