### ISSUE TITLE
Agendar execução de Pipelines

### ISSUE THREAD

**Issue by rfalexandre** [eubr-bigsea/citrus#424]
Ao tentar agendar a execução de uma Pipeline está sendo gerado um internal server error.

Obs: discutir se faz sentido agendar Pipelines para uma data/hora no passado.

**Comment by waltersf** [comment]
Melhorei a mensagem de erro. É uma regra que está sendo violada. Pra agendar, todas as etapas têm que estar associadas a fluxos de trabalho. 
Favor testar.
