### ISSUE TITLE
Disparo/Execução de uma Pipeline

### ISSUE THREAD

**Issue by rfalexandre** [eubr-bigsea/citrus#425]
Aparentemente não está sendo possível executar uma Pipeline que eventualmente seria inicializada manualmente.

Obs: a Pipeline não aparece no histórico de execuções ao ser criada. Logo, não é possível realizar o disparo manual.

**Comment by waltersf** [comment]
Poderia dar mais detalhes, como por exemplo, qual o id da pipeline? Pq a princípio, o que está habilitado para disparo são os passos de uma pipeline run.

**Comment by rfalexandre** [comment]
Acredito que a correção do agendamento da Pipeline tenha possibilitado a ocorrencia da Pipeline no histórico de execuções. Dessa forma é possível executá-la manualmente. (Problema corrigido).

Obs: ajustar a mensagem de agendamento em caso de etapas não vinculadas a um fluxo: "Pelo menus uma etapa da pipeline não está associada a um fluxo de trabalho." --> "Ao menos...".

Verificar a edição do Workflow vinculado a uma etapa: entrar em uma Pipeline, Configurações, clicar no botão Alterar, clicar em Salvar. Em tese, deveria salvar a etapa sem o vínculo a um workflow. No entanto, permanece com o Workflow anterior vinculado.

Verifique a mecânica da associação de workflows: ao entrar em Configurações da Etapa 1, clicar no botão Alterar, aparentemente se perde o vínculo com o workflow já atribuído. Logo após, clique em outra etapa. A Configuração dessa outra etapa não é carregada corretamente.

Questão de usabilidade: incluir um botão Voltar na tela de edição de Pipelines.

Obs: considere a Pipeline de ID 68 nos teste.

**Comment by waltersf** [comment]
O que está marcado como "OK" foi resolvido. Gentileza testar.

> Acredito que a correção do agendamento da Pipeline tenha possibilitado a ocorrencia da Pipeline no histórico de execuções. Dessa forma é possível executá-la manualmente. (Problema corrigido).
Ok
> 
> Obs: ajustar a mensagem de agendamento em caso de etapas não vinculadas a um fluxo: "Pelo menus uma etapa da pipeline não está associada a um fluxo de trabalho." --> "Ao menos...".
OK

> 
> Verificar a edição do Workflow vinculado a uma etapa: entrar em uma Pipeline, Configurações, clicar no botão Alterar, clicar em Salvar. Em tese, deveria salvar a etapa sem o vínculo a um workflow. No entanto, permanece com o Workflow anterior vinculado.
> 
> Verifique a mecânica da associação de workflows: ao entrar em Configurações da Etapa 1, clicar no botão Alterar, aparentemente se perde o vínculo com o workflow já atribuído. Logo após, clique em outra etapa. A Configuração dessa outra etapa não é carregada corretamente.
NOK. Temos que permitir desassociar um fluxo? 
> 
> Questão de usabilidade: incluir um botão Voltar na tela de edição de Pipelines.
> 
OK

> Obs: considere a Pipeline de ID 68 nos teste.
