### ISSUE TITLE
Agendamento de Pipelines

### ISSUE THREAD

**Issue by rfalexandre** [eubr-bigsea/citrus#427]
1. O agendamento das Pipelines está considerando o mês subsequente ao informado no momento do agendamento.
2. Está sendo possível agendar mais de uma vez a mesma Pipeline para o mesmo mês/ano. Talvez a execução seja duplicada.
3. Não é possível "cancelar/descartar" um agendamento realizado de forma equivocada.

**Comment by rfalexandre** [comment]
Pode ser que o botão "Cancelar" tenha como objetivo "cancelar/descartar" um agendamento realizado de forma equivocada. No entanto, é necessário verificar se ele está funciondo corretamente. Aparentemente o Status da Pipeline Run não está sendo alterado ao clicar no botão "Cancelar".

**Comment by waltersf** [comment]
> Pode ser que o botão "Cancelar" tenha como objetivo "cancelar/descartar" um agendamento realizado de forma equivocada. No entanto, é necessário verificar se ele está funcionando corretamente. Aparentemente o Status da Pipeline Run não está sendo alterado ao clicar no botão "Cancelar".

OK, por favor, teste. Acabei de atualizar a versão

**Comment by waltersf** [comment]
> 1. O agendamento das Pipelines está considerando o mês subsequente ao informado no momento do agendamento.
Ok, corrigido. Favor testar
> 2. Está sendo possível agendar mais de uma vez a mesma Pipeline para o mesmo mês/ano. Talvez a execução seja duplicada.
A princípio, vou deixar. Fica como melhoria.
> 3. Não é possível "cancelar/descartar" um agendamento realizado de forma equivocada.
Agora o cancelar está funcionando. Favor testar

**Comment by rfalexandre** [comment]
O botão de "Cancelar" a execução está funcionando parcialmente. Perceba que ao cancelar a execução de uma Pipeline que possui mais de uma atriuição para o mesmo mês/ano, ela é cancelada mas as demais continuam PENDENTE. Daí não é possível cancelar as demais pois deve ter alguma lógica vinculada ao botão que verifica o status da execução por mês/dia. 

Verifique a execução de ID 44.

Obs: talvez seja interessante padronizar o botão de "Voltar" como na tela de detalhamento de execuções (https://dev.lemonade.org.br/jobs/1/1)
