### ISSUE TITLE
Disparo/Execução de Etapa

### ISSUE THREAD

**Issue by pedroMendesR** [eubr-bigsea/citrus#428]
Quando vamos na página de execução da Pipeline e clicamos no botão azul que executa a Etapa, ele abre um popup confirmando se é para executar ou não, tanto as opções "Não" e "Sim" disparam a Etapa.

edit: Sair da janela também dispara a execução, ou seja, o evento de "close" do componente está chamando o disparo.

![image](https://github.com/user-attachments/assets/90f457ae-e01d-4108-8ed3-de7295c31371)

**Comment by waltersf** [comment]
Corrigido. Favor testar. Lembrar de fazer refresh na página.
