### ISSUE TITLE
Inconsistência em PipelineRun já criada ao editar a sua abstração Pipeline

### ISSUE THREAD

**Issue by pedroMendesR** [eubr-bigsea/citrus#429]
Para um teste, realizei as seguintes operações ordenadas:

1. Criei uma Pipeline com 2 etapas (Etapa 1 e Etapa 2) e instanciei a PipelineRun;
2. Rodei a PipelineRun e tudo OK;
3. Alterei a Pipeline adicionando uma nova etapa (Etapa 3)
    3.1. Esta mudança não refletiu na instância já criada de PipelineRun, só nas novas, o que está OK
4. Alterei  a Pipeline novamente, mudando o workflow da Etapa 1
    4.1. Esta mudança reflete na instância já criada de PipelineRun que possui a Etapa 1.

Acredito que isto possa ser o previsto mesmo, a PipelineRun é criada somente com uma lista de etapas e não reflete a criação de novas etapas na Pipeline, mas penso que, se a lógica for garantir persistência, também deveria ser assim para os workflows dentro das etapas da PipelineRun.

**Comment by waltersf** [comment]
Não será corrigido. Deixaremos assim por enquanto.
