### ISSUE TITLE
Pequenos bugs e sugestão

### ISSUE THREAD

**Issue by pedroMendesR** [eubr-bigsea/citrus#430]
[BUG] No workflow com SQL/Python, ao selecionar a opção de executar uma única célula, todas as células Python estão sendo executadas também.

[BUG] Ao criar nova etapa na Pipeline, na janela que abre para inserir nome e descrição, associar uma workflow ou criar uma nova nesta tela não está funcionando.

[SUGESTÃO] Trocar nome do novo status "WAITING_INTERVENTION" por "INCONSISTENT"

[SUGESTÃO] Quando se tratar de Workflow com células SQL, usar o link na etapa da Pipeline que vai para a página de células, não para a tradicional página de workflows.

**Comment by waltersf** [comment]
"WAITING_INTERVENTION" é porque precisa de intervenção humana. Não entendi porque trocar por "INCONSISTENT".

**Comment by pedroMendesR** [comment]
Só sugeri a mudança de nome porque "WAITING_INTERVENTION" é muito grande mesmo, trocar por outro nome como "INCONSISTENT" tem um pouco de perda de informação, mas fica mais sucinto e o usuário eventualmente se acostumaria com o que isso quer dizer, "se está inconsistente, precisa de uma intervenção".
