### ISSUE TITLE
Versão dev - Gráfico de dispersão - Usar valores sem agregar não funciona ao tentar usar subgráficos

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#431]
Usando uma base de dados com o Quarteto de Anscombe, os gráficos de dispersão para cada conjunto do quarteto foram construídos corretamente usando filtro (dataset == "I" a dataset == "IV")  e usando "Usar valores sem agregar".

Entretanto, ao tentar usar subgráficos separando pelo atributo dataset, só executou sem erro usando alguma função de agregação diferente de "Usar valores sem agregar".

Figura do resultado usando AVG, por exemplo. O que nesse caso não atende, pois o conjunto IV contém vários valores de Y para X=8.

![image](https://github.com/user-attachments/assets/5a04a7af-bfa9-4ff4-b8e0-a6bd36a5cf30)

Com "Usar valores sem agregar", dá o seguinte erro (somente com subgráficos):

![image](https://github.com/user-attachments/assets/fd55b176-c393-4775-8eb7-d7fbda75e103)

**Comment by waltersf** [comment]
Corrigido. Favor testar.

**Comment by educsantos** [comment]
Funcionou. Obrigado.
