### ISSUE TITLE
Sugestão: Incluir opção de ordenação de subgráficos

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#432]
Seria interessante ter um campo para controlar a ordem de exibição dos subgráficos.

Por padrão, seguir a ordem dos valores do atributo de separação.

Atualmente, os subgráficos são posicionados provavelmente conforme a ordem em que ficam prontos. Assim, são exibidos em ordens diferentes a cada rodada e sem o controle do usuário.

**Comment by waltersf** [comment]
Feito. Favor testar e se possível, com outros tipos de gráficos.

**Comment by educsantos** [comment]
Funcionando para a maioria. 

Parece-me que está seguindo a ordem alfanumérica dos valores do atributo da separação, correto?

Testei com dispersão, barras horizontais e barras horizontais empilhadas. OK para cada um desses tipos de gráficos.

Com pizza, parece seguir a ordem em que ficam prontos, porque muda a cada rodada. 

Ilustrando (fluxo 839) - note a ordem de racacor modificando a cada rodada:

![image](https://github.com/user-attachments/assets/fc747f03-2b40-4e25-b61c-7db2a39f0c4c)

![image](https://github.com/user-attachments/assets/1dcab179-42d3-44e0-b2e2-bb1b940b0e35)

![image](https://github.com/user-attachments/assets/39dbed96-8cfc-4805-862b-1b3365264ae3)

**Comment by waltersf** [comment]
@educsantos Feito. Favor testar.

**Comment by educsantos** [comment]
Está OK
