### ISSUE TITLE
Possíveis bugs durante o agedamento dos passos

### ISSUE THREAD

**Issue by SamuelLipovetsky** [eubr-bigsea/citrus#434]
Ao tentar modificar o agendamento de uma etapa de uma pipeline com somente 1 etapa, o citrus reporta que a operação foi salva, mas os dados não persistem
![image](https://github.com/user-attachments/assets/b59c7368-deb5-4d29-b6e1-984ef9f05d7e)
ao recarregar a página , esse estado do agedamento do step é perdido
![image](https://github.com/user-attachments/assets/d5fe7e62-bef4-4159-b8a2-29efa115c5ec)
Usando a api do tahiti para recuperar a pipeline reporta o passo sem informações de agedamento, a única maneira que consegui fazer funcionar e ter pelo menos 2 passos antes de modificar as  informaçoes de agedamento das etapas

**Comment by waltersf** [comment]
Corrigido. Aproveitei e limitei as opções para agendamento. Ficaram apenas mensal e disparada pelo usuário.
Importante: o início, no caso de mensal, agora não solicita os dias mais, apenas o dia inicial. É importante o agendador tratar dois casos:
- Se o agendamento for mensal e startDay for igual a "last": roda no último dia do mês
- Se por alguma razão, for escolhido o dia 29, 30 ou 31, para fevereiro, o dia 28 roda também. Para os meses com 30 dias, se for escolhido dia 31, no dia 30 também. Em resumo, algo como (hojeEhUltimoDiaMes && (startDay >= diaDeHoje || startDay == 'last'))
