### ISSUE TITLE
Fluxos de Trabalho - Fontes de Dados

### ISSUE THREAD

**Issue by rfalexandre** [eubr-bigsea/citrus#438]
A opção de Ajuda disponível em FLuxo de Trabalho disponibiliza uma aba que deve listar os atributos de fontes de dados utilizadas pelo usuário. Caso apenas 1 fonte de dados esteja sendo utilizada, os atributos são listados sem erro. No entanto, ao registrar mais de uma fonte de dados, os atributos da segunda fonte não são apresentados corretamente. É necessário regarregar a página para a listagem correta.

De forma similar, ao registrar uma nova fonte de dados, as opções SELECT e INSERT disponíveis como wizard ao usuário não estão funcionando. É necessário recarregar a página para que funcione corretamente.

**Comment by waltersf** [comment]
Corrigido. Favor testar.

**Comment by rfalexandre** [comment]
Problema corrigido.
