### ISSUE TITLE
Erro na operação Carregar Modelo

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#48]
Fluxo número 75.

Aparentemente o erro é causado por um problema com a operação Salvar Modelo

![image](https://user-images.githubusercontent.com/14841688/52499241-1a83b600-2bc2-11e9-8e0d-6c2fdde5b3a8.png)

**Comment by waltersf** [comment]
@matheusrleal 
Esse bug está corrigido. Mas por favor, teste e se houver problema, reabra a issue. Vi que a cada execução, um modelo foi criado. Avalie se a operação SaveModel está com problemas ou não.
