### ISSUE TITLE
Random Forest Classifier - Minors

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#52]
1) The word  'impureza'  is wrongly written into the hyper-parameter with this name:

![image](https://user-images.githubusercontent.com/24958541/52536772-14b6dd80-2d46-11e9-8f42-cfe69990487d.png)

**Recommendation**: Replace 'Inpureza Gini'  by 'Coeficiente Gini'.

=================

2) Hyper-parameter 'Number of Trees' (or 'Número de árvores') is not appearing. (I believe the parameter 'Impureza' is repeated and the second one just means the 'Number of Trees':

![image](https://user-images.githubusercontent.com/24958541/52536868-10d78b00-2d47-11e9-89d7-3cd684b3fa1f.png)

**Comment by alexgcsa** [comment]
-> Hyper-parameter 'Number of Trees' (or 'Número de árvores') is not appearing.

**Comment by waltersf** [comment]
Fixed.
