### ISSUE TITLE
Percentual splitting should show what is training and what is testing.

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#53]
The weights should indicate what part is training and what part is testing.

It is a bit confusing. Until now, I don't know what is part of the data is set to be the training:

![image](https://user-images.githubusercontent.com/24958541/52537185-cce68500-2d4a-11e9-85dc-7af8b6e625f5.png)

**Comment by alexgcsa** [comment]
Perhaps indicating  after the hyper-parameter Weights.

**Comment by waltersf** [comment]
New version states more clearly which part is what.
