### ISSUE TITLE
Percentual splitting is not returning the correct number of instances.

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#55]
I set the Percentual splitting operation to give me half of the samples for training and the other half for testing. 

My dataset has 150 samples/examples. It should return 75 for each set. However, it returned 85 for the test.

The workflow id is 86. I used to test the perceptron algorithm.

Next, the confusion matrix:

![image](https://user-images.githubusercontent.com/24958541/52542058-266aa600-2d83-11e9-93f9-71c3811a6b18.png)

**Comment by waltersf** [comment]
Spark implements random split because for large data sets, it does not need to count and then divide.

**Comment by alexgcsa** [comment]
Wouldn't this randomness should be applied only to select the instances?
I mean, ff you have a dataset with 1000 instances and set the weights equally (50% for training / 50% for testing), Spark should select 500 instances at random for training and 500 instances for testing.

Now, if it is choosing 600 for training and 400 for testing, this parameter 'Weights' does not mean what is supposed to mean.

**Comment by waltersf** [comment]
Added a better description to the operation.

**Comment by waltersf** [comment]
Fixed
