### ISSUE TITLE
PCA and Locality-sensitive hashing are only working with 'Vectorize attribute(s)'

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#58]
Workflow id: 90.

===============================

Invalid or missing parameters: requirement failed: Column petallength must be of type struct<type:tinyint,size:int,indices:array<int>,values:array<double>> but was actually decimal(5,1).

**Comment by alexgcsa** [comment]
The working workflow (by using the 'Vectorize attribute(s)') has the id 91.

**Comment by alexgcsa** [comment]
One minor: you have to type something for the hyper-parameter "PCA output attribute*", even this coming with a default string value.

**Comment by alexgcsa** [comment]
The same error happens in the operation 'Locality-sensitive hashing'.

You can see the workflow  92 not working and the 93 working.

**Comment by waltersf** [comment]
Work is in progress.

**Comment by waltersf** [comment]
Fixed.
