### ISSUE TITLE
Download results of the operation

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#59]
As Lemonade only supports seeing the first 50 records regarding the results of the operation. 

However, sometimes we would like to check these results on the entire dataset. 

Therefore, Lemonade should have an option that downloads all results of a given operation.

**Comment by alexgcsa** [comment]
perhaps, Lemonade should compact all the log into a file (or a set of files into a zip file), making available to download.

**Comment by waltersf** [comment]
You can use the Save data operation if the output is a data frame. This must be explicitly defined by the users, otherwise, we'd be saving many useless files in the system.
