### ISSUE TITLE
Implement "dirty" check in edit forms

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citrus#76]
Test if user changed something in the forms for data source, workflow and dashboard and is leaving the screen. If so, ask him if he wants to save the form before leaving the screen.

**Comment by waltersf** [comment]
Implemented. Please, @alexgcsa, help us testing.

**Comment by alexgcsa** [comment]
Alright. I'm going to test it.

**Comment by alexgcsa** [comment]
Working correctly:

![image](https://user-images.githubusercontent.com/24958541/58144206-e50c5100-7c23-11e9-98ba-5d5d2acf7596.png)

**Comment by alexgcsa** [comment]
Closing the issue.
