### ISSUE TITLE
Multi-layer perceptron new error

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#80]
Walter,

When executing multi-layer perceptron, the following error appears:

![image](https://user-images.githubusercontent.com/24958541/53534282-e9214a80-3adc-11e9-902f-c4be86db43cb.png)

The id of the workflow is 72.

**Comment by alexgcsa** [comment]
It was working before changing the name of the method.

**Comment by alexgcsa** [comment]
Besides, "Prediction attribute (new)" is also not being updated from the algorithm to the "Evaluate model".

This was happening in the last version.

**Comment by waltersf** [comment]
@alexgcsa Could it be caused because there are 4 species of Iris and you're specifying an output of 8?

**Comment by alexgcsa** [comment]
@waltersf sorry, my mistake.
