### ISSUE TITLE
Error at Citrus Module

### ISSUE THREAD

**Issue by leal2020** [eubr-bigsea/citrus#85]
When compiler lemonade, i got the following error at Citrus Module.
https://pastebin.com/kchS2wVm

**Comment by waltersf** [comment]
@guimaluf Could you please check it? Maybe something related to docker version.

**Comment by guimaluf** [comment]
docker-lemonade webhook which update submodules were with firewall issues.
it is fixed. @leal2020 please update your docker-lemonade repository, it should work.
