### ISSUE TITLE
Inferir esquema da fonte de dados a partir dos metadados

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#86]
Ao selecionar Inferir esquema da fonte de dados a partir dos metadados e executar, a coluna de metadados aparece vazia.

Fluxo: 2

![image](https://user-images.githubusercontent.com/8696951/53913196-86c6cd80-4039-11e9-859f-7dceb746b7bc.png)

**Comment by waltersf** [comment]
@karenstemartins Esta informação está vazia porque não há nada nesse caso mesmo. Ficou confuso porque há metadados no Lemonade e também no Spark. Vou mudar o rótulo para Metadados (Spark).

**Comment by waltersf** [comment]
Rótulo alterado
