### ISSUE TITLE
Erro Agrupar Linhas por Função

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#87]
Fluxo 12 não funciona corretamente.

Resultado esperado:

![image](https://user-images.githubusercontent.com/8696951/53958370-9f79c680-40bf-11e9-8e7f-39120144874b.png)

Resultado encontrado:

![image](https://user-images.githubusercontent.com/8696951/53958404-bc15fe80-40bf-11e9-994b-7a623c987db0.png)

**Comment by waltersf** [comment]
@karenstemartins Não use essa base do Titanic. Ela está com formato incorreto.
