### ISSUE TITLE
Erro na operação Executar código Python

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#88]
Fluxo 6, a vizualização parou de funcionar.

![image](https://user-images.githubusercontent.com/8696951/53958857-d56b7a80-40c0-11e9-93cc-aec23408fdaa.png)

Na execução de número 792 funcionou perfeitamente:

![image](https://user-images.githubusercontent.com/8696951/53958828-c4bb0480-40c0-11e9-8d29-e8668fb9ac88.png)

**Comment by sauloantuness** [comment]
There is a problem with the caipirinha response. As you can see, in the response of the last job 884 (https://lemonade.ctweb.inweb.org.br/caipirinha/visualizations/884/be4a9f01-cd38-4e1e-8023-25ff7ebc8819?token=123456) the values of the series are being returned as null. Also, the values of x and y are missing.

![image](https://user-images.githubusercontent.com/1711258/54044255-45efc580-41ad-11e9-8657-5cc3244e61df.png)

Below, the response of the job  792 quoted as OK. (https://lemonade.ctweb.inweb.org.br/caipirinha/visualizations/792/be4a9f01-cd38-4e1e-8023-25ff7ebc8819?token=123456)

![image](https://user-images.githubusercontent.com/1711258/54044303-628bfd80-41ad-11e9-8fb7-5fa238fcfdc4.png)

Have you seen this before @waltersf ?

**Comment by waltersf** [comment]
@karenstemartins No código Python, você usa os seguintes parâmetros:
y_axis_attribute = [ "petallength" ]
x_axis_attribute = [ "class" ]

Mas no código, geral o dataframe com os nomes Petal_Length e Species. Na base, os nomes são realmente petallength e class.
