### ISSUE TITLE
Logistic regression issue

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#89]
Hello,

When running logistic regression to perform classification, we have to choose the family (binomial, multinomial or automatic). 

When we have a multiclass problem, the only valid option for the classifier is the multinomial family. However, when I run the classifier in a multiclass problem with the binomial family, the workflow is finished with success.

I was wondering if Lemonade should return an error instead of completing the task.

**workflow id:** 106

**Comment by waltersf** [comment]
Parameter was not working (all tests were applying multinomial). Deployed version is fixed now, but the error message is in English only.

**Comment by waltersf** [comment]
Fixed

**Comment by waltersf** [comment]
Important: I changed 2 options for LR: the family (Binomial) and the option to perform one-vs-one classification in order to raise and simulate the error.

**Comment by alexgcsa** [comment]
Could you translate the error to PT-BR?

It is outputting:
"Parâmetro inválido ou ausente: requirement failed: Binomial family only supports 1 or 2 outcome classes but found 4."

I would translate to:
"Falha de requisitos: A família Binomial somente suporta um ou dois valores categóricos para o atributo com o rótulo."

**Comment by alexgcsa** [comment]
Tested. Waiting for updates.

**Comment by waltersf** [comment]
Alex, it is fixed since a couple of weeks. For example, see job https://lemonade.ctweb.inweb.org.br/#/jobs/1/5623. See message: "Parâmetro inválido ou ausente: Família binomial suporta apenas 1 ou 2 classes resultantes, mas foram encontradas 4". The translation is different from yours, but I think it is enough.

**Comment by alexgcsa** [comment]
Hi Walter,

It is ok. Closing the issue now. I was not aware that the problem was fixed.

Thanks,

Alex
