### ISSUE TITLE
Delete button is not working (on Firefox?)

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#9]
The delete button (to delete a dataset or a workflow) is not working on Firefox (not sure if this issue can happen on other browsers).

This button is working for Opera and Chrome.

**Comment by waltersf** [comment]
Fixed. Please, test it.

**Comment by alexgcsa** [comment]
Tested. It works now.

If not tested yet, it would be interesting to test the same button on Microsoft Edge and Pale Moon, for instance.

I am going to do this asap.
