### ISSUE TITLE
PCA - Change the name of  a hyper-parameter

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#93]
The hyper-parameter with the name 'Atributo com o vetor de features' is not correct anymore as we do not need the vectorization to perform PCA:

![image](https://user-images.githubusercontent.com/24958541/54094194-cebd5b80-437d-11e9-86a5-a7a13b55a8e5.png)

**Comment by alexgcsa** [comment]
Perhaps it is better to use 'Atributos de entrada'.

**Comment by alexgcsa** [comment]
Perhaps, I would also change the name of the hyper-parameter 'Atributo para saída do ACP' to 'Atributo de saída do PCA'.

**Comment by waltersf** [comment]
Duplicated #126. Fixed
