### ISSUE TITLE
Evaluate model - change the name of two (hyper-)parameters and correct metric list

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#98]
Replace "Atributo usado como label" by "Atributo com o rótulo". 
Replace "Atributo usado para predição" by "Atributo com a predição".

This is to standardize with the other operations.

![image](https://user-images.githubusercontent.com/24958541/54536354-55220080-496f-11e9-863e-4ee7a1de952e.png)

Please, correct the list of metrics as well:

![image](https://user-images.githubusercontent.com/24958541/54536867-49830980-4970-11e9-907e-e98de2b3692a.png)

**Comment by waltersf** [comment]
Fixed
